### ISSUE TITLE
Minor bugs that need further investigation

### ISSUE THREAD

**Issue by acoolstraw** [labwc/labwc#332] opened 2022-05-19 14:50 UTC
This is a collection of bugs that are a bit too vague and minor for a separate issue

- [ ] Occasionally, some applications have a weird bug with the SSD when dragged, the buttons go on the other side and the rest of it disappears (will investigate further)
- [ ] GIMP does not respect yambar's offset when it starts, the title bar covers yambar.
- [ ] #337
- [ ] #339

#### Nvidia specific:
- [ ] Windows (it seems only windowed fullscreen games) flicker if there's another window above them. This seems to only happen with Nvidia drivers.
- [ ] #338

#### Done:
- [x] #309
- [x] #331
- [x] #340
- [x] #317
- [x] #336

**Comment by acoolstraw** [comment] 2022-05-21 10:54
[ ] Drawing on swappy (`grim -g "$(slurp)" - | swappy -f -`) is buggy, as for some reason the brush poiner is offset diagonally, but your actual cursor stays where you originally started the drawing (bottom right side of the diagonal line) 
![image](https://user-images.githubusercontent.com/45886986/169648320-50174647-b65f-478f-af50-3e3b285e9ca2.png)

**Comment by johanmalm** [comment] 2022-05-21 11:27
It would be easier to discuss these if you split them into separate issues. Numbers are free 😄  
Any checking you can do on sway to confirm that it’s definitely a labwc would be a great help.

**Comment by acoolstraw** [comment] 2022-05-21 11:40
Will split the issue and test whether it happens on sway

**Comment by johanmalm** [comment] 2022-05-22 18:33
> * [ ]  Drawing on swappy (`grim -g "$(slurp)" - | swappy -f -`) is buggy, as for some reason the brush poiner is offset diagonally, but your actual cursor stays where you originally started the drawing

Caused by 

https://github.com/labwc/labwc/blob/fbcdf38b52bb5a9635962e346c4f82e8c932ec89/src/cursor.c#L296

The offset is because `scene_xdg_surface_update_position()` takes into account the invisible border of the view and positions the node accordingly in https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/types/scene/xdg_shell.c#L57

**Comment by acoolstraw** [comment] 2022-08-28 11:52
> Occasionally, some applications have a weird bug with the SSD when dragged, the buttons go on the other side and the rest of it disappears (will investigate further)
this no longer seems to happen

**Comment by johanmalm** [comment] 2022-09-12 19:23
Could you review and update?

**Comment by Consolatis** [comment] 2022-12-20 20:09
Will close this issue for now, feel free to update / open new issues.

**Closed by Consolatis** 2022-12-20 20:09 UTC
Labels: bug, investigation required
