### ISSUE TITLE
Stuck alt-tab cycle-window OSD

### ISSUE THREAD

**Issue by johanmalm** [labwc/labwc#98] opened 2021-10-26 20:43 UTC
It's been reported that someone got stuck in the alt-tab cycler and that has higher priority than switching to a tty so couldn't escape it.

Need to find a way of reproducing the issue before trying to fix it.

Worth considering:
1. Maybe need to move the cycle_view related code from keyboard_modifiers_notify() to handle_compositor_keybindings().
2. After handle_keybinding() is called for WL_KEYBOARD_KEY_STATE_PRESSED, maybe we need to prevent the equivalent WL_KEYBOARD_KEY_STATE_RELEASED being forwarded to clients.

**Comment by 01micko** [comment] 2021-11-29 11:06
This bug affects my productivity almost daily so @ARDiDo , @Joshua-Ashton any ideas? The `sway/input/keyboard.c` line does look like a way forward to me, but I really have no idea.

**Comment by 01micko** [comment] 2021-11-29 20:10
More info as I've been capturing unique logs over past weeks. (only last 10 lines posted each log).
Note that I at least 3 times a week to latest git version and do run a patch to run as root; see https://github.com/puppylinux-woof-CE/woof-CE/issues/2563. The error is quite consistent and persistent!

`labwc -d >> /var/log/labwc${$}.log`

```log

/var/log/labwc10789.log
00:00:00.001 [INFO] [libseat] [libseat/libseat.c:67] Seat opened with backend 'builtin'
00:00:00.001 [INFO] [libseat] [libseat/backend/seatd.c:222] Enabling seat
00:00:00.001 [INFO] [backend/session/session.c:110] Successfully loaded libseat session
00:00:00.003 [INFO] [backend/backend.c:219] Found 1 GPUs
00:00:00.003 [INFO] [backend/drm/backend.c:183] Initializing DRM backend for /dev/dri/card0 (radeon)
00:00:00.003 [DEBUG] [backend/drm/drm.c:81] Atomic modesetting unsupported, using legacy DRM interface
00:00:00.003 [DEBUG] [backend/drm/drm.c:98] ADDFB2 modifiers unsupported
00:00:00.003 [INFO] [backend/drm/drm.c:259] Found 2 DRM CRTCs
00:00:00.003 [INFO] [backend/drm/drm.c:186] Found 2 DRM planes
00:00:00.003 [ERROR] [../src/server.c:80] unable to drop root

/var/log/labwc12570.log
00:00:18.013 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
00:00:18.029 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
00:00:18.029 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
(EE) failed to read Wayland events: Broken pipe
warn: wayland.c:691: disconnected from Wayland
00:00:20.333 [DEBUG] [backend/drm/drm.c:1026] connector DVI-D-1: De-allocating CRTC 0
00:00:20.389 [DEBUG] [backend/drm/drm.c:1026] connector VGA-1: De-allocating CRTC 1
00:00:20.423 [INFO] [libseat] [seatd/seat.c:413] No clients on seat0 to activate
00:00:20.524 [INFO] [libseat] [seatd/seat.c:519] Closed client 1 on seat0
00:00:20.524 [INFO] [libseat] [seatd/seat.c:198] Removed client 1 from seat0

/var/log/labwc12739.log
00:02:41.044 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
00:02:41.052 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
00:02:41.052 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
(EE) failed to read Wayland events: Broken pipe
warn: wayland.c:691: disconnected from Wayland
00:02:42.339 [DEBUG] [backend/drm/drm.c:1026] connector DVI-D-1: De-allocating CRTC 0
00:02:42.394 [DEBUG] [backend/drm/drm.c:1026] connector VGA-1: De-allocating CRTC 1
00:02:42.428 [INFO] [libseat] [seatd/seat.c:413] No clients on seat0 to activate
00:02:42.530 [INFO] [libseat] [seatd/seat.c:519] Closed client 1 on seat0
00:02:42.530 [INFO] [libseat] [seatd/seat.c:198] Removed client 1 from seat0

/var/log/labwc13376.log
04:23:55.097 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
04:23:55.105 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
04:23:55.105 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
(EE) failed to read Wayland events: Broken pipe
warn: wayland.c:691: disconnected from Wayland
04:23:56.690 [DEBUG] [backend/drm/drm.c:1026] connector DVI-D-1: De-allocating CRTC 0
04:23:56.736 [DEBUG] [backend/drm/drm.c:1026] connector VGA-1: De-allocating CRTC 1
04:23:56.770 [INFO] [libseat] [seatd/seat.c:413] No clients on seat0 to activate
04:23:56.869 [INFO] [libseat] [seatd/seat.c:519] Closed client 1 on seat0
04:23:56.869 [INFO] [libseat] [seatd/seat.c:198] Removed client 1 from seat0

/var/log/labwc21167.log
00:01:31.057 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
00:01:31.073 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
00:01:31.073 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
(EE) failed to read Wayland events: Broken pipe
warn: wayland.c:691: disconnected from Wayland
00:01:33.510 [DEBUG] [backend/drm/drm.c:1026] connector DVI-D-1: De-allocating CRTC 0
00:01:33.567 [DEBUG] [backend/drm/drm.c:1026] connector VGA-1: De-allocating CRTC 1
00:01:33.601 [INFO] [libseat] [seatd/seat.c:413] No clients on seat0 to activate
00:01:33.700 [INFO] [libseat] [seatd/seat.c:519] Closed client 1 on seat0
00:01:33.700 [INFO] [libseat] [seatd/seat.c:198] Removed client 1 from seat0

/var/log/labwc21791.log
00:00:56.946 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
00:00:56.954 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
00:00:56.954 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
(EE) failed to read Wayland events: Broken pipe
warn: wayland.c:691: disconnected from Wayland
00:00:58.429 [DEBUG] [backend/drm/drm.c:1026] connector DVI-D-1: De-allocating CRTC 0
00:00:58.478 [DEBUG] [backend/drm/drm.c:1026] connector VGA-1: De-allocating CRTC 1
00:00:58.512 [INFO] [libseat] [seatd/seat.c:413] No clients on seat0 to activate
00:00:58.608 [INFO] [libseat] [seatd/seat.c:519] Closed client 1 on seat0
00:00:58.608 [INFO] [libseat] [seatd/seat.c:198] Removed client 1 from seat0

/var/log/labwc22414.log
00:04:00.150 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
00:04:00.158 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
00:04:00.158 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
(EE) failed to read Wayland events: Broken pipe
warn: wayland.c:691: disconnected from Wayland
00:04:01.783 [DEBUG] [backend/drm/drm.c:1026] connector DVI-D-1: De-allocating CRTC 0
00:04:01.831 [DEBUG] [backend/drm/drm.c:1026] connector VGA-1: De-allocating CRTC 1
00:04:01.866 [INFO] [libseat] [seatd/seat.c:413] No clients on seat0 to activate
00:04:01.966 [INFO] [libseat] [seatd/seat.c:519] Closed client 1 on seat0
00:04:01.966 [INFO] [libseat] [seatd/seat.c:198] Removed client 1 from seat0

/var/log/labwc22703.log
00:01:15.999 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
00:01:16.063 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
00:01:16.063 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
(EE) failed to read Wayland events: Broken pipe
warn: wayland.c:691: disconnected from Wayland
00:01:17.692 [DEBUG] [backend/drm/drm.c:1026] connector DVI-D-1: De-allocating CRTC 0
00:01:17.737 [DEBUG] [backend/drm/drm.c:1026] connector VGA-1: De-allocating CRTC 1
00:01:17.771 [INFO] [libseat] [seatd/seat.c:413] No clients on seat0 to activate
00:01:17.868 [INFO] [libseat] [seatd/seat.c:519] Closed client 1 on seat0
00:01:17.868 [INFO] [libseat] [seatd/seat.c:198] Removed client 1 from seat0

/var/log/labwc22903.log
00:16:11.051 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
00:16:11.059 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
00:16:11.067 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
(EE) failed to read Wayland events: Broken pipe
warn: wayland.c:691: disconnected from Wayland
00:16:12.809 [DEBUG] [backend/drm/drm.c:1026] connector DVI-D-1: De-allocating CRTC 0
00:16:12.865 [DEBUG] [backend/drm/drm.c:1026] connector VGA-1: De-allocating CRTC 1
00:16:12.899 [INFO] [libseat] [seatd/seat.c:413] No clients on seat0 to activate
00:16:13.012 [INFO] [libseat] [seatd/seat.c:519] Closed client 1 on seat0
00:16:13.012 [INFO] [libseat] [seatd/seat.c:198] Removed client 1 from seat0

/var/log/labwc23441.log
02:54:05.368 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
02:54:05.384 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
02:54:05.385 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
(EE) failed to read Wayland events: Broken pipe
warn: wayland.c:691: disconnected from Wayland
02:54:06.738 [DEBUG] [backend/drm/drm.c:1026] connector DVI-D-1: De-allocating CRTC 0
02:54:06.791 [DEBUG] [backend/drm/drm.c:1026] connector VGA-1: De-allocating CRTC 1
02:54:06.826 [INFO] [libseat] [seatd/seat.c:413] No clients on seat0 to activate
02:54:06.923 [INFO] [libseat] [seatd/seat.c:519] Closed client 1 on seat0
02:54:06.923 [INFO] [libseat] [seatd/seat.c:198] Removed client 1 from seat0

/var/log/labwc26225.log
00:24:46.601 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'HDMI-A-1'
00:24:46.601 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
00:24:46.601 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
(EE) failed to read Wayland events: Broken pipe
warn: wayland.c:691: disconnected from Wayland
00:24:48.775 [DEBUG] [backend/drm/drm.c:1026] connector DVI-D-1: De-allocating CRTC 0
00:24:48.828 [DEBUG] [backend/drm/drm.c:1026] connector VGA-1: De-allocating CRTC 1
00:24:48.862 [INFO] [libseat] [seatd/seat.c:413] No clients on seat0 to activate
00:24:49.091 [INFO] [libseat] [seatd/seat.c:519] Closed client 1 on seat0
00:24:49.091 [INFO] [libseat] [seatd/seat.c:198] Removed client 1 from seat0

/var/log/labwc2682.log
16:50:52.732 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
16:50:52.732 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
16:50:52.740 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
16:50:52.740 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
16:50:52.748 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
16:50:52.748 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
16:50:52.756 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
16:50:52.756 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
(EE) failed to read Wayland events: Broken pipe
warn: wayland.c:691: disconnected from Wayland

/var/log/labwc27511.log
00:02:20.103 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
00:02:20.103 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
00:02:20.103 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'HDMI-A-1'
(EE) failed to read Wayland events: Broken pipe
warn: wayland.c:691: disconnected from Wayland
00:02:21.604 [DEBUG] [backend/drm/drm.c:1026] connector DVI-D-1: De-allocating CRTC 0
00:02:21.657 [DEBUG] [backend/drm/drm.c:1026] connector VGA-1: De-allocating CRTC 1
00:02:21.691 [INFO] [libseat] [seatd/seat.c:413] No clients on seat0 to activate
00:02:21.786 [INFO] [libseat] [seatd/seat.c:519] Closed client 1 on seat0
00:02:21.786 [INFO] [libseat] [seatd/seat.c:198] Removed client 1 from seat0

/var/log/labwc28371.log
00:03:07.285 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
00:03:07.285 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
00:03:07.285 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'HDMI-A-1'
(EE) failed to read Wayland events: Broken pipe
warn: wayland.c:691: disconnected from Wayland
00:03:08.748 [DEBUG] [backend/drm/drm.c:1026] connector DVI-D-1: De-allocating CRTC 0
00:03:08.808 [DEBUG] [backend/drm/drm.c:1026] connector VGA-1: De-allocating CRTC 1
00:03:08.842 [INFO] [libseat] [seatd/seat.c:413] No clients on seat0 to activate
00:03:08.937 [INFO] [libseat] [seatd/seat.c:519] Closed client 1 on seat0
00:03:08.937 [INFO] [libseat] [seatd/seat.c:198] Removed client 1 from seat0

/var/log/labwc28630.log
00:00:59.134 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'VGA-1'
00:00:59.134 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'DVI-D-1'
00:00:59.134 [DEBUG] [types/output/cursor.c:395] Falling back to software cursor on output 'HDMI-A-1'
(EE)warn:  wayland.c:691: failed to read Wayland events: Broken pipe
disconnected from Wayland
00:01:00.837 [DEBUG] [backend/drm/drm.c:1026] connector DVI-D-1: De-allocating CRTC 0
00:01:00.893 [DEBUG] [backend/drm/drm.c:1026] connector VGA-1: De-allocating CRTC 1
00:01:00.927 [INFO] [libseat] [seatd/seat.c:413] No clients on seat0 to activate
00:01:01.040 [INFO] [libseat] [seatd/seat.c:519] Closed client 1 on seat0
00:01:01.040 [INFO] [libseat] [seatd/seat.c:198] Removed client 1 from seat0
```

Most of the time I can just exit the session and restart but as you see in the logs sometimes the system hangs and a hard reboot is needed.

**Comment by johanmalm** [comment] 2021-11-29 21:31
@01micko I didn’t realise it was so persistent. I’ve tried with geany, but still can’t reproduce it.

How do the logs differ when you get the alt-tab issue vs when you don’t.

Unfortunately I won’t be able to look at it until the weekend at the earliest, so it will have to wait unless anyone has time.

**Comment by 01micko** [comment] 2021-11-29 23:34
I really don't know if geany is to blame or not. It's just I nearly always have it, firefox and foot or lxterminal open all the time and it seems to usually happen when I want to alt-tab to geany! It could well just be a coincidence.

**Comment by 01micko** [comment] 2021-11-30 08:17
I'm beginning to think it may be a `libinput` bug. I'll try to update it.

**Comment by 01micko** [comment] 2021-11-30 19:33
I have a partial log with just libinput entries

`grep 'libinput' /var/log/labwc5908.log >~/lwc-libinput.log`

Thousands of the 404 warning. Don't know if it's of any use. Maybe I need to run with debug symbols?


```
00:00:00.277 [DEBUG] [backend/libinput/backend.c:87] Starting libinput backend
00:00:00.489 [DEBUG] [backend/libinput/events.c:95] Added Power Button [0:1]
00:00:00.492 [DEBUG] [backend/libinput/events.c:95] Added Power Button [0:1]
00:00:00.494 [DEBUG] [backend/libinput/events.c:95] Added PixArt USB Optical Mouse [2362:9488]
00:00:00.494 [INFO] [../src/seat.c:52] Skipping libinput configuration for device
00:00:00.494 [DEBUG] [backend/libinput/events.c:95] Added   USB Keyboard [1241:5890]
00:00:00.497 [DEBUG] [backend/libinput/events.c:95] Added   USB Keyboard System Control [1241:5890]
00:00:00.500 [DEBUG] [backend/libinput/events.c:95] Added   USB Keyboard Consumer Control [1241:5890]
00:00:00.503 [DEBUG] [backend/libinput/events.c:95] Added Eee PC WMI hotkeys [0:0]
00:00:00.505 [DEBUG] [backend/libinput/backend.c:133] libinput successfully initialized
00:16:47.528 [DEBUG] [backend/libinput/events.c:328] Unknown libinput event 404
00:16:47.592 [DEBUG] [backend/libinput/events.c:328] Unknown libinput event 404
00:16:47.640 [DEBUG] [backend/libinput/events.c:328] Unknown libinput event 404
00:17:31.487 [DEBUG] [backend/libinput/events.c:328] Unknown libinput event 404
(snipped over 2000 lines out of this partial log)

08:03:59.730 [DEBUG] [backend/libinput/events.c:328] Unknown libinput event 404
08:03:59.786 [DEBUG] [backend/libinput/events.c:328] Unknown libinput event 404
08:03:59.834 [DEBUG] [backend/libinput/events.c:328] Unknown libinput event 404
08:04:07.595 [DEBUG] [backend/libinput/events.c:328] Unknown libinput event 404
```

**Comment by 01micko** [comment] 2021-12-05 00:00
Working much better now, but geany IDE still has issues, so I'm calling it a geany bug. Closing.

**Comment by johanmalm** [comment] 2021-12-05 09:16
@01micko I think we ought to try not sending the released key events to the client unless the press event was sent (i.e. for key bindings).
Your geany behaviour is a good “test” for this, so keen to give it a shot - just haven’t had time yet.
So suggest we keep the issue open if you’re happy to.

**Comment by 01micko** [comment] 2021-12-05 09:29
> So suggest we keep the issue open if you’re happy to.

Sure, no problem.

**Comment by bi4k8** [comment] 2021-12-12 03:37
I was just able to reproduce this issue by accidentally leaving Caps Lock on.

**Comment by ARDiDo** [comment] 2021-12-13 00:26
Thanks for finding that @bi4k8. It works for Num Lock as well.
We might need to make an exception for them in any_modifiers_pressed().
However, we still likely need to implement something like @johanmalm suggested.

**Comment by 01micko** [comment] 2021-12-13 05:59
Maybe why I have so many issues, I often leave numlock on, and why it seems so intermittent.

**Comment by 01micko** [comment] 2021-12-13 08:13
Now that I'm more aware of my `numlock` status I've had geany open and lxterminal with firefox, editing scripts, minimising geany while testing, then alt-tab raising geany without issue.

**Comment by 01micko** [comment] 2021-12-17 23:21
Last post here 5 days ago and computer uptime is:
```
~$ uptime
 09:16:11 up 5 days,  2:36,  0 users,  load average: 0.73, 0.50, 0.33
```
Simply being aware of the numlock status solves this for me so now we know the cause. Nice to be fixed for **0.4.0** :+1:

**Comment by ARDiDo** [comment] 2021-12-18 15:37
https://github.com/labwc/labwc/commit/57cc72b49e39da50ccd8a08631c57f2c6f5ca1a7 fixes this on my end. Closing.

**Closed by ARDiDo** 2021-12-18 15:37 UTC
Labels: bug

**Comment by 01micko** [comment] 2021-12-18 21:11
Fixed here :smiley:
