### ISSUE TITLE
Input to nano, the pop didn't follow the cursor in labwc7.2

### ISSUE THREAD

**Issue by knm100** [labwc/labwc#1886] opened 2024-06-08 04:42 UTC
Arch Linux+LXQT2.0.1(waylnad session)+Labwc7.2,  Input to nano with fcitx5, the pop didn't follow the cursor in labwc7.2
but  Arch Linux+LXQT2.0.1(waylnad session)+Kwin_wayland,  it is fine.
Is it a issue of labwc, or fcitx5?

**Comment by tokyo4j** [comment] 2024-06-08 11:47
I tried fcitx5+alacritty+nano and it worked fine. What terminal emulator are you using?

![labwc72-alacritty-fcitx5-nano](https://github.com/labwc/labwc/assets/22029524/c1266192-b345-4d1b-8a0b-d91bb0865f8a)

**Comment by tokyo4j** [comment] 2024-06-09 16:40
I could not reproduce the difference when running konsole under labwc and kwin_wayland.

In my setup, the popup of fcitx5-mozc follows the cursor on alacritty while it doesn't until I hit Enter on konsole. And this behavior is common both in labwc and kwin_wayland. 

https://github.com/labwc/labwc/assets/22029524/04504fea-b908-4dfb-abf5-f8ae6a75173f

So my questions are:
- What do you mean by saying "the pop didn't follow the cursor"? Is the popup position updated when you commit the composited text (like when I hit Enter with fcitx5-mozc)?
- What Fcitx5 module (e.g. fcitx5-rime) are you using?
- What's the value in `QT_IM_MODULE`?

**Comment by knm100** [comment] 2024-06-10 03:07
>In my setup, the popup of fcitx5-mozc follows the cursor on alacritty while it doesn't until I hit Enter on konsole. And this behavior is common both in labwc and kwin_wayland

Plesa see my screenshot,  Popup of fcitx5-rime(I am using fcitx5-rime)  is far away from where the cursor.
![swappy-20240610-103932](https://github.com/labwc/labwc/assets/166389780/40c93858-0f1f-4090-a42a-46d02d1f37a1)

![swappy-20240610-103934](https://github.com/labwc/labwc/assets/166389780/6eb3c0f5-19b4-4a2f-838a-e03971c0b9c8)

>What's the value in QT_IM_MODULE?

I tried to set  “QT_IM_MODULE=fcitx5”  and  “QT_IM_MODULE=” ，  There is no difference between the two ways for me

**Comment by knm100** [comment] 2024-06-10 03:28
Sorry, I made a waste of your time.    after setting QT_IM_MODULE=fcitx,  It is fine.

 would you like to mark me clear?  why do I need to set QT_IM_MODULE=fcitx in labwc, but don't need to set this variable in kwin.    both in the two compositor should input text with text input v3.

**Comment by tokyo4j** [comment] 2024-06-13 05:49
Sorry for late reply.

Qt only supports text-input-v2, not v3. And KWin supports all of text-input-v1, v2, v3.
So my suspicion is that Qt (konsole) first tries to use `fcitx5` IM module, falls back to text-input-v2, then falls back to IBus interface or something, which cannot place IME popup correctly.

I cannot get why `QT_IM_MODULE=fcitx5` doesn't work but `QT_IM_MODULE=fcitx` works in your setup. Have you installed `fcitx5-qt` package?

**Comment by knm100** [comment] 2024-06-13 07:05
I just tried QT_IM_MODULE=fcixt5,  it can work.   Before, it didn't work, it should be that I made a typing error.
fcitx5-qt is installed with fcitx5, fcitx5-gtk.

If qt only supports text-input-v2,  Before setting the QT_IM_MODULE, all QT programs should encounter this issue.
 But if i didn't run nano in konsole, it is normal to input in konsole.    
regardless of whether QT_IM_MODULE is set or not, the input of any other QT program is normal.

**Comment by tokyo4j** [comment] 2024-06-13 08:28
Sorry, I was wrong. Qt supports text-input-v3 (I confirmed with `WAYLAND_DEBUG`), but I guess it doesn't work well when the application are not using input field components offered by Qt. I had a quick look at konsole's source code and found it draws cursor and text using QPainter ([link](https://github.com/KDE/konsole/blob/master/src/terminalDisplay/TerminalPainter.cpp)). So perhaps this problem can be fixed by adding some extra code in konsole to let Qt update the position of IME popup.

I don't think this problem is specific to nano because the position of IME popup is not updated also in fish shell when I start konsole with `QT_IM_MODULE= konsole`.

https://github.com/labwc/labwc/assets/22029524/06667b08-a108-49f0-a9eb-da4fdd2523c9

**Comment by knm100** [comment] 2024-06-13 13:12
Yes, I tried again , there are the same issue in konsole and qterminal.  this issue has nothing to do with nano.
kate can be entered normally
Thank you for helping me figure this out

**Closed** 2024-06-13 13:24 UTC
