### ISSUE TITLE
xfce4-panel

### ISSUE THREAD

**Issue by johanmalm** [labwc/labwc#661] opened 2022-12-03 18:57 UTC
This is just to share that there is a version of `xfce4-panel` which works on `labwc`. It was shared on the #labwc IRC channel last night and I thought some build instruction and references were worthy of some wider publicity :smile:

https://gitlab.xfce.org/xfce/xfce4-panel/-/merge_requests/103

@Tamaranch - copied for info as the main dev.

These are the steps I took on Arch Linux to get it going:

1. I installed the following from the AUR:

- xfce4-dev-tools-devel
- garcon-devel
- libxfce4util-devel
- libxfce4ui-devel

2. I then ran the following:

```
pacman -S exo gtk-layer-shell
```

```
git clone https://gitlab.xfce.org/kelnos/libxfce4windowing
cd libxfce4windowing
./autogen --prefix=/usr
make
sudo make install
cd ..
```

```
git clone --branch=wayland-xfw https://gitlab.xfce.org/Tamaranch/xfce4-panel
cd xfce-panel
./autogen --prefix=/usr
make
sudo make install
```

**Comment by johanmalm** [comment] 2022-12-03 18:57
https://user-images.githubusercontent.com/6955353/205457348-e9cd56a0-a0f6-4f19-83ff-d4980e8ed597.mp4

**Comment by johanmalm** [comment] 2022-12-03 19:07
[recording.webm](https://user-images.githubusercontent.com/6955353/205457696-fb4e6a5d-621d-400b-a111-5f5a73f88ee9.webm)

**Comment by johanmalm** [comment] 2022-12-03 20:58
@Tamaranch  It works very well. Most impressive.

Found one issue - right clicking on a plugin and select 'move' results in a crash. Not looked at the code (yet).
[recording.webm](https://user-images.githubusercontent.com/6955353/205461836-2323a4a5-239a-4aa1-97ea-24162c5208ae.webm)

**Comment by johanmalm** [comment] 2022-12-03 21:03
@Tamarance also, there seems to be an occasional glitch with foreign-toplevel in that client `title` / `app_id` is missing for a short while. It might be an out-by-one protocol read/write type issue.

In this example, I've just opened to terminals and you can same the title/app_ids missing.

![20221203_21h00m08s_grim](https://user-images.githubusercontent.com/6955353/205461976-46343195-e11c-41f4-b571-d988c0a8d662.png)

**Comment by Tamaranch** [comment] 2022-12-03 22:03
> Can raise issues on xfce.gitlab if you prefer

Yes please add new comments on the merge request, it is better to have it centralized there if possible (and we can make threads there too, it's convenient in this case).

For the plugin move I know about it, it's a dnd issue that I'm afraid is coming from GTK. I've left it out for now (I should maybe grey out the menu entry by the way). It is possible to move plugins via the preferences dialog, items tab, in the meantime.

Thanks for testing and for opening this issue, it's nice :smiley:

**Comment by droc12345** [comment] 2022-12-06 16:05
Sweet, I used to use the xfce panel with openbox. I'll have to give it a try.

**Comment by Tamaranch** [comment] 2022-12-07 12:12
> there seems to be an occasional glitch with foreign-toplevel in that client `title` / `app_id` is missing for a short while. It might be an out-by-one protocol read/write type issue.

I can't reproduce that. I tried to install Sakura and to activate the window grouping by application, without result. Besides, I have never noticed this before. I'm probably missing something...

**Comment by johanmalm** [comment] 2022-12-07 21:35
> > there seems to be an occasional glitch with foreign-toplevel in that client `title` / `app_id` is missing for a short while. It might be an out-by-one protocol read/write type issue.
> 
> I can't reproduce that. I tried to install Sakura and to activate window grouping by application, without result. Besides, I have never noticed this before. I'm probably missing something...

I think it depended a bit on how I opened the clients. From memory, I saw the issues when opening with bemenu, but not when opening from the root-menu.
I would be able to test/investigate until the weekend. 
Will try to write down steps to reproduce and see if I can narrow it down a particular line in the code.

**Comment by Tamaranch** [comment] 2022-12-11 18:29
> I'm not sure if this is a know issue, but some plugins stays on top on fullscreen apps (including games, mpv, etc...).

Yes I expected this to happen, because at the moment external plugins are on the overlay layer. I think it would be better to put them on the top layer like the panel, but that will cause other problems...

That said, shouldn't an overlay application opened after the panel (actually here: after its external plugins) be on top of them? I haven't tested this well yet...

> Also, the audio plugin keeps crashing and asking to be removed from the panel (only when audio is playing)

It is very possible that plugins that are not provided with the panel (most of them) work more or less well or even crash. These are separate Xfce components that will have to be ported to Wayland  as we go along, and it might take some time.

Most of them seemed to work pretty well though, in the few tests I did, see https://wiki.xfce.org/releng/wayland_roadmap#panel_plugins.

**Important note**: as external plugins support is still experimental, I added a hidden setting to force all plugins to run as internal, i.e. in the same process as the panel.
To create and enable it, run
```
xfconf-query -c xfce4-panel -p /force-all-internal -t bool -s true --create
```
Of course, now if a plugin crashes like PulseAudio above, the panel will crash with it. This is one of the problems of internal plugins...

**Comment by Consolatis** [comment] 2022-12-11 18:52
> That said, shouldn't an overlay application opened after the panel (actually here: after its external plugins) be on top of them?

For things using the layershell protocol and the overlay layer (like a lockscreen or on-screen-keyboard): yes. For simple XDG windows which request fullscreen: no. They are usually rendered between the `Top` and `Overlay` layers.

**Comment by johanmalm** [comment] 2022-12-11 19:12
> XDG-popups spawned by layershell clients (e.g. GTK menus) are always rendered on top of everything else as far as I remember.

Yes. Node z-order set here.

https://github.com/labwc/labwc/blob/e4aa7cef765a81a6911839de16644eceeb2fb5e9/src/output.c#L163-L177

**Comment by Tamaranch** [comment] 2022-12-13 22:50
> I'm not sure if this is a know issue, but some plugins stays on top on fullscreen apps (including games, mpv, etc...).

@ScarecrowDM It should be good now :)

**Comment by varbhat** [comment] 2023-01-11 10:02
@johanmalm @Consolatis 
Does auto hiding of panel work?

**Comment by Tamaranch** [comment] 2023-01-11 10:18
@varbhat it should. Be sure to use last panel version though (4.19.0 is out now).

**Comment by ScarecrowDM** [comment] 2023-11-23 21:01
Hello.
It seems that the following pull request (https://github.com/labwc/labwc/pull/1237) broke xfce4-panel behavior while gaming in full screen. Prior to that being merged, the panel was hiding perfectly fine. 
![20231123_16h56m57s_grim](https://github.com/labwc/labwc/assets/6687106/c56a36ed-30b7-4af1-a5e1-01290fa1b228)

**Comment by Consolatis** [comment] 2023-11-23 21:53
Is the panel visible all the time when gaming in fullscreen or does it require `A-Tab` or changing workspaces or similar?

**Comment by ScarecrowDM** [comment] 2023-11-24 00:37
Just launching the game will trigger the bug: the affected games will occupy the entire screen but the panel will remain at the top (i can see the game running through the panel transparency).
Alt+tab doesn't change anything and I don't have workspaces configured right now.

I can't reproduce this with firefox, mpv and some games.
But it happens every time with games like Alan Wake 2 (wine), Starfield (steam+proton) and Cyberpunk (steam+proton), Quake 1 Remaster (steam-native).
If I alternate between windowed and fullscreen on AW2 it will trigger the panel to hide, but the same trick doesn't work on Cyberpunk.

I'm using xfce4-panel-devel-4.19.2-1, btw

**Comment by Consolatis** [comment] 2023-11-24 00:51
So it doesn't happen with all games, interesting. Maybe those games first use a usual fullscreen and then switch over to unmanaged surfaces or something along that line.  Thoughts @johanmalm @jlindgren90 ?

This sounds like something we should fix before 0.6.6. But so far I am not sure why it happens now and not before #1237.

**Comment by ScarecrowDM** [comment] 2023-11-24 01:36
I just setup a couple of workspaces to test:
If I alternate to workspace 2 while the affected game is running and then comeback to workspace 1, the panel will hide immediately (the game will be minimized but I can select it with alt+tab and the panel will remain hidden). It could used as a workaround for now. :)

**Comment by johanmalm** [comment] 2023-11-24 14:40
Not sure. I guess it relates to the call to `desktop_update_top_layer_visiblity()` in `src/view.c`.
https://github.com/labwc/labwc/blob/1b8e404c9c6078088ba4b4eb48ae971702810497/src/view.c#L1135

I suspect the easiest approach is the run the games with some printfs to see what's going on.
Steam won't let me in at the moment, and I suspect the games will be too big for my modest setup anyway.
@Joshua-Ashton - don't know if you've got any spare capacity to help with this one?

**Comment by Consolatis** [comment] 2023-11-25 00:10
> Not sure. I guess it relates to the call to `desktop_update_top_layer_visiblity()` in `src/view.c`.

Right, but the exact same thing is called when switching workspaces. So it appears to work in the 2nd case when switching back to the workspace but doesn't work in the first case when starting the game. `view->output`, `view->workspace`, `view->scene_tree` and `view->fullscreen` all seem set correctly from what I can see before `view_set_fullscreen()` is called in `xwayland_view_map()` so this is a quite mysterious change in behavior for me.

**Comment by johanmalm** [comment] 2023-11-25 07:19
Yes, I'm in the same place as you.
I looked through the code path yesterday, and it's not obvious to me what could have caused the change.

**Comment by Consolatis** [comment] 2023-11-25 07:47
Oh, `view_is_focusable()` checks for `view->surface` which is set after the call to `view_set_fullscreen()`

**Comment by johanmalm** [comment] 2023-11-25 09:16
Nice catch!

So revert how it was in set_fullscreen() but leave as is in workspace_switch_to() and view_destroy()?

**Comment by Consolatis** [comment] 2023-11-25 09:50
I think we could just move the `view->surface` assignment a bit further up in `xwayland_view_map()` (and maybe also fix the TODO comment there by destroying the view, but up for debate if that should be done within the same PR / before the release).

**Closed** 2023-11-25 20:11 UTC

**Comment by DrVektor** [comment] 2024-02-25 20:11
because labwc is like openbox. On the desktop it is not possible for the mouse pointer to create a selection square and select an object with left click. But in xfce desktop it is possible in lxde desktop. Will it also be possible on xfce wayland desktop?

**Comment by johanmalm** [comment] 2024-03-06 19:45
> because labwc is like openbox. On the desktop it is not possible for the mouse pointer to create a selection square and select an object with left click. But in xfce desktop it is possible in lxde desktop. Will it also be possible on xfce wayland desktop?

It depends on what desktop client you use. It's perfectly doable on Wayland. For example if you use `pcmanfm-qt --desktop` with window rules you can do it. The LXQt projects are just moving to Qt6.5 with more native Wayland support (including the layer-shell protocol), but have not tried it with that yet.
