### ISSUE TITLE
Window switcher switching back to the previous window immediately

### ISSUE THREAD

**Issue by charbelnicolas** [labwc/labwc#1640] opened 2024-03-19 00:10 UTC
One of the last few commits in the last day or two has introduced a bug in the window switcher that makes it switch back to the previous window immediately after selecting a window. It happens most of the time when cycling through the windows switcher. Please see the attached video. This is with the latest git version.

https://github.com/labwc/labwc/assets/14960414/79b9ab90-61c3-41a4-8a51-31065c79e4bb

**Comment by charbelnicolas** [comment] 2024-03-19 00:15
It's actually quite a showstopper bug not being able to switch windows....

**Comment by Consolatis** [comment] 2024-03-19 00:16
Thanks for the report. Will try to investigate later.
For now I suggest using an older commit or the last release.

**Comment by charbelnicolas** [comment] 2024-03-19 00:24
I don't know what triggered it but it's working fine now... It had never happened to me before and I've been using labwc for more than a month now...

**Comment by Consolatis** [comment] 2024-03-19 01:49
Depending on how you compile labwc, sometimes meson seems to mix things up and doesn't re-compile some parts that it should re-compile. That can then cause various random symptoms like this, recreating the build directory (e.g. via `meson setup new_build; meson compile -C new_build`) should help.

I am closing this issue for now but please comment / reopen if it happens again. We had some major changes to how the OSD shows and switches between windows somewhat recently so it is quite possible that we missed something there.

**Comment by droc12345** [comment] 2024-03-25 12:43
Looks like it's the original way (not all workspaces).

Which version of labwc does this happen on, or which git commit?

**Comment by droc12345** [comment] 2024-03-25 23:45
I usually use foot with firefox also, FF is the wayland only version.
And I can't seem to reproduce that problem.

Are you running the latest git version?

and by disappear, you mean it doesn't show the window at all, but it's still active?
ie, if you do a ps does foot still show?

**Comment by droc12345** [comment] 2024-03-26 00:32
are you using outlines and/or preview (window switcher rc setting)?

**Comment by tokyo4j** [comment] 2024-03-27 07:45
I don't know if this is the same problem, but by following the procedure below, a window can be hidden, although it seems to be activated from waybar: 

1. Minimize a window
2. Select the window by Alt-Tab
3. Move cursor on the preview
4. Release Alt-Tab

https://github.com/labwc/labwc/assets/22029524/8d3e4eaa-f7f5-41f9-819d-839a17b7518f

**Comment by tokyo4j** [comment] 2024-03-27 07:56
@charbelnicolas Does applying this patch solve the problem?
```diff
diff --git a/src/input/cursor.c b/src/input/cursor.c
index ad5782e..3115522 100644
--- a/src/input/cursor.c
+++ b/src/input/cursor.c
@@ -506,6 +506,10 @@ cursor_get_resize_edges(struct wlr_cursor *cursor, struct cursor_context *ctx)
 static void
 process_cursor_motion(struct server *server, uint32_t time)
 {
+	if (server->osd_state.cycle_view) {
+		return;
+	}
+
 	/* If the mode is non-passthrough, delegate to those functions. */
 	if (server->input_mode == LAB_INPUT_STATE_MOVE) {
 		process_cursor_move(server, time);

```

**Comment by droc12345** [comment] 2024-03-27 09:14
It's during the preview, that if the window is minimized, when cycling through, the system gets confused,
or some internal state it's carrying gets inconsistent. ie. the window is minimized but the system thinks it's not. I'll look at that later.

**Comment by Consolatis** [comment] 2024-03-27 10:34
This indeed sounds like some race condition with the preview. Not quite sure what exactly but I'll try to look into this in the coming days.

**Comment by tokyo4j** [comment] 2024-03-28 07:07
I couldn't reproduce this issue when I tried @pablo-888's method for 5 minutes, after I applied my patch. That's so strange.

**Comment by tokyo4j** [comment] 2024-03-28 09:48
I finally figured out why I couldn't reproduce it!
I was using following mouse settings `rc.xml`:
```xml
    <context name="Title">
      <mousebind button="Left" action="Press">
        <action name="Focus" />
        <action name="Raise" />
      </mousebind>
      <mousebind button="Left" action="Drag">
        <action name="Move" />
      </mousebind>
      <mousebind button="Left" action="DoubleClick">
        <action name="ToggleMaximize" />
      </mousebind>
    </context>
```
But if I moved `<mousebind button="Left" action="Press">` to `<context name="TitleBar">` (which is default), the problem happens.

**Comment by Consolatis** [comment] 2024-03-28 09:53
Hm.. so it appears we have to clock all mouse input while in `A-Tab` (e.g. `cycle_view` is set). If that works its nice to know that there is a workaround.  However I still don't understand why this then causes the describe behavior, something happening randomly is usually a very bad sign.

**Comment by tokyo4j** [comment] 2024-03-28 11:33
After some debugging, I found this bug happens with procedure below:

1. Show preview of the minimized window by pressing Alt-Tab
2. Press the iconify button
3. Release Alt-Tab to finish OSD
4. Release the iconify button

Usually, 3 comes before 2, but when repeating this procedure so fast, sometimes 3 comes after 2 and this bug happens.

**Comment by charbelnicolas** [comment] 2024-03-28 14:11
> That's very weird indeed. I can pretty much reproduce it every time within a minute or less.
> 
> OP's problem seems to have gone away (?) I don't really care about previews so it's not a big deal. If nobody can reproduce it and Consolatis doesn't find anything whenever he looks into it then i'm cool with just closing this as previously intended/leaving it alone tbh 😁. Maybe nobody else ever runs into it who knows.

I was only able to reproduce it that one time and it has not happened to me again. I do have preview enabled on the window switcher.

**Comment by charbelnicolas** [comment] 2024-03-28 14:17
Never mind I was able to reproduce it again just now on demand...

**Comment by charbelnicolas** [comment] 2024-03-28 14:43
If I disable the preview on the window switcher it won't even switch to the window that is misbehaving.

Check the video below. Can you notice that when I switch windows the `[xdg-shell] kitty charbel - rc.xml - NVIM` window loses focus but still won't change to the other `[xdg-shell] kitty ~` window?

If I switch between `[xdg-shell] kitty charbel - rc.xml - NVIM` and `[xdg-shell] chromium Window...` it works. It is only the `[xdg-shell] kitty ~` window that has glitched out.

https://github.com/labwc/labwc/assets/14960414/6f157907-0282-4c7e-bc51-2f6ecdf4f74d

**Comment by tokyo4j** [comment] 2024-03-28 14:45
> Mouse movement seems fine to me though.

I guess we need to disable `<followMouse>` when OSD is activated, as it has similar effects as `<action name="Focus" /><action name="Raise" />` against minimized windows.

So the patch will look like:
```diff
diff --git a/src/input/cursor.c b/src/input/cursor.c
index eb359e7..cec9db2 100644
--- a/src/input/cursor.c
+++ b/src/input/cursor.c
@@ -529,7 +529,8 @@ process_cursor_motion(struct server *server, uint32_t time)
 		dnd_icons_move(seat, seat->cursor->x, seat->cursor->y);
 	}
 
-	if ((ctx.view || ctx.surface) && rc.focus_follow_mouse) {
+	if ((ctx.view || ctx.surface) && rc.focus_follow_mouse
+			&& !server->osd_state.cycle_view) {
 		desktop_focus_view_or_surface(seat, ctx.view, ctx.surface,
 			rc.raise_on_focus);
 	}

```

**Comment by charbelnicolas** [comment] 2024-03-28 14:51
> > Mouse movement seems fine to me though.
> 
> I guess we need to disable `<followMouse>` when OSD is activated, as it has similar effects as `<action name="Focus" /><action name="Raise" />` against minimized windows.
> 
> So the patch will look like:
> 
> ```diff
> diff --git a/src/input/cursor.c b/src/input/cursor.c
> index eb359e7..cec9db2 100644
> --- a/src/input/cursor.c
> +++ b/src/input/cursor.c
> @@ -529,7 +529,8 @@ process_cursor_motion(struct server *server, uint32_t time)
>  		dnd_icons_move(seat, seat->cursor->x, seat->cursor->y);
>  	}
>  
> -	if ((ctx.view || ctx.surface) && rc.focus_follow_mouse) {
> +	if ((ctx.view || ctx.surface) && rc.focus_follow_mouse
> +			&& !server->osd_state.cycle_view) {
>  		desktop_focus_view_or_surface(seat, ctx.view, ctx.surface,
>  			rc.raise_on_focus);
>  	}
> ```

Yes, for sure it has something to do with `<followMouse>`. This is what I have on my config:
```
<focus>

	<followMouse>yes</followMouse>
	<followMouseRequiresMovement>yes</followMouseRequiresMovement>
	<raiseOnFocus>no</raiseOnFocus>

</focus>
```

**Comment by tokyo4j** [comment] 2024-03-28 15:07
(Sorry I'm so slow at writing English and my last comment was not related to yours)

I think the video you posted doesn't contradict with what we've observed so far.

Can you apply [this patch](https://github.com/labwc/labwc/files/14791532/patch.txt) and see the problem still exists? If it does, maybe we're missing something.

**Comment by charbelnicolas** [comment] 2024-03-28 15:10
I can now reproduce it 100% of the time.

The way to reproduce it is to minimize/iconify the window you want to glitch then bring up the window switcher with ALT-TAB and then move your cursor to the actual window being previewed so it gains focus and then let go of ALT (or whatever you have set up as modifier key).

**Comment by charbelnicolas** [comment] 2024-03-28 15:13
https://github.com/labwc/labwc/assets/14960414/7e59ec8c-759d-487a-ae93-bab2bee144e4

**Comment by charbelnicolas** [comment] 2024-03-28 15:19
> (Sorry I'm so slow at writing English and my last comment was not related to yours)
> 
> I think the video you posted doesn't contradict with what we've observed so far.
> 
> Can you apply [this patch](https://github.com/labwc/labwc/files/14791532/patch.txt) and see the problem still exists? If it does, maybe we're missing something.

I've never applied patches, I only use the AUR on Arch Linux to get the latest git version to update. I don't really know the proper way to do it. Maybe someone else can try!

**Comment by Consolatis** [comment] 2024-03-28 16:00
> The way to reproduce it is to minimize/iconify the window you want to glitch then bring up the window switcher with ALT-TAB and then move your cursor to the actual window being previewed so it gains focus and then let go of ALT (or whatever you have set up as modifier key).

> Yes, for sure it has something to do with `<followMouse>`. This is what I have on my config:
> 
> ```xml
> <focus>
> 	<followMouse>yes</followMouse>
> 	<followMouseRequiresMovement>yes</followMouseRequiresMovement>
> 	<raiseOnFocus>no</raiseOnFocus>
> </focus>
> ```

That appears to point to the focus action doing something weird in combination with the OSD preview of a minimized window (`raiseOnFocus` not being enabled).

**Comment by Consolatis** [comment] 2024-03-28 16:19
> > Mouse movement seems fine to me though.
> 
> I guess we need to disable `<followMouse>` when OSD is activated, as it has similar effects as `<action name="Focus" /><action name="Raise" />` against minimized windows.
> 
> So the patch will look like:
> 
> ```diff
> diff --git a/src/input/cursor.c b/src/input/cursor.c
> index eb359e7..cec9db2 100644
> --- a/src/input/cursor.c
> +++ b/src/input/cursor.c
> @@ -529,7 +529,8 @@ process_cursor_motion(struct server *server, uint32_t time)
>  		dnd_icons_move(seat, seat->cursor->x, seat->cursor->y);
>  	}
>  
> -	if ((ctx.view || ctx.surface) && rc.focus_follow_mouse) {
> +	if ((ctx.view || ctx.surface) && rc.focus_follow_mouse
> +			&& !server->osd_state.cycle_view) {
>  		desktop_focus_view_or_surface(seat, ctx.view, ctx.surface,
>  			rc.raise_on_focus);
>  	}
> ```

This looks good to me, combined with preventing the execution of mouse button actions when in A-Tab mode this should hopefully fix the issue.

**Comment by Consolatis** [comment] 2024-03-29 02:01
@tokyo4j combined your patch with two more checks in the action handlers on cursor click / release:
- #1668

Testing would be appreciated.

**Comment by tokyo4j** [comment] 2024-03-29 05:30
I found another bug similar to this: we can still make the inconsistent state by activating the previewed window from `wlr-foreign-toplevel-management` clients like waybar:

https://github.com/labwc/labwc/assets/22029524/cb15009b-7312-4e5f-ace9-e635d48ec3de

I guess we can address it as another issue though.

**Comment by Consolatis** [comment] 2024-03-29 08:25
> I found another bug similar to this: we can still make the inconsistent state by activating the previewed window from `wlr-foreign-toplevel-management` clients like waybar:

Thanks, should be handled in the PR as well now.

**Closed** 2024-05-05 20:05 UTC
Labels: bug, help wanted, investigation required
