### ISSUE TITLE
single-clicking on chromium's titlebar unmaximizes/untiles the window.

### ISSUE THREAD

**Issue by pablo-888** [labwc/labwc#2008] opened 2024-07-20 04:06 UTC
Just tested it on Wayfire and Sway and it doesn't happen there. (doesn't happen on Xorg either). When I maximize or tile chromium and then click one time on an empty section of the titlebar, the window resizes and untiles itself (this behaviour should only happen on double-clicks). It  also doesn't happen if you click on a tab, only the empty space. 

I mostly use firefox so I don't know how long this has been happening sadly or if it only happens to a very small number of people.

**Comment by tokyo4j** [comment] 2024-07-20 06:23
I think this is duplicate of #1968.

I agree it's annoying, because Chromium's "new tab" button is so small and I often click empty space which un-tiles the window immediately. For touchpad user, this issue was fixed by #1593.

**Closed** 2024-07-20 06:27 UTC
Labels: duplicate
