### ISSUE TITLE
GTK3 windows that are snapped to the edge of the screen don't return to their non-tiled state after restoring.

### ISSUE THREAD

**Issue by pablo-888** [labwc/labwc#1531] opened 2024-02-14 17:26 UTC
They remain squared and the shadows are gone. I didn't notice this before because I just happened to be using a square theme that didn't have any shadows to begin with.  As a workaround I just set 'notifyClient' to never for now.

I thought it was weird because I remember seeing a video of it working on that feature's PR but then I noticed the demo was made with a GTK4 app (Nautilus) so I tried the same (gnome-todo/endeavour) and that one worked fine. Only GTK3 apps have this problem for me.

**Comment by ahesford** [comment] 2024-02-15 03:16
I can't reproduce this issue. My copy of Endeavour, from Void Linux, uses GTK4. I have several GTK+3 applications, including `gtk3-demo`, `cheese`, `gedit`, `simple-scan` and `wdisplays`. When I snap those windows to edges, rounded corners on client-side decorations do *not* disappear. When I drag the windows away from the edge, the shadows are still visible.

**Comment by ahesford** [comment] 2024-02-15 04:17
Very interesting. I think the best long-term solution for labwc would be window actions that allow control over the tiling notification behavior of individual, misbehaving clients in addition to the global switch available now.

**Comment by jp7677** [comment] 2024-02-15 19:10
Looking at Gnome/Mutter (version 45 on Wayland with Fedora 39) on my machine, the snapping and unsnapping effects do work there correctly with GTK3 apps, whereas the same applications refuse to unset the snapping appearance on labwc. But no idea though if Gnome/mutter just carries a work around or handle that differently.

**Comment by jp7677** [comment] 2024-02-16 07:55
This is the PR that introduced tiling support for GTK3 https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6629 released with GTK3 3.24.39

**Comment by Consolatis** [comment] 2024-02-25 00:15
> Looking at Gnome/Mutter (45.4 on Wayland with Fedora 39, GTK3 3.24.41) on my machine, the snapping and unsnapping effects do work there correctly with GTK3 apps, whereas the same applications refuse to unset the snapping appearance on labwc. But no idea though if Gnome/mutter just carries a work around or handle that differently.

A `WAYLAND_DEBUG=1` log of the two might help here.

**Comment by jp7677** [comment] 2024-02-26 18:08
Here are two log file, from labwc and Gnome, recorded with `WAYLAND_DEBUG=1 tilix`. What I did was snap, un-snap and close using keys. I hope this provides something useful.

labwc: 
[labwc.log](https://github.com/labwc/labwc/files/14408885/labwc.log)

Gnome:
[gnome.log](https://github.com/labwc/labwc/files/14408899/gnome.log)

**Comment by Consolatis** [comment] 2024-02-26 18:46
Hm..
labwc:
```
[2764987.072] xdg_toplevel@32.configure(1602, 1188, array[4]
[2766332.114] xdg_toplevel@32.configure(1720, 1404, array[20])
[2766660.096] xdg_toplevel@32.configure(1602, 1188, array[4])
```
gnome:
```
[2868914.608] xdg_toplevel@39.configure(1602, 1188, array[4])
[2869713.328] xdg_toplevel@39.configure(1720, 1408, array[16])
[2870191.705] xdg_toplevel@39.configure(1602, 1188, array[4]
```

Sadly, the `WAYLAND_DEBUG` output doesn't parse the array contents at all and just states its overall size. So we only know that both - labwc and gnome - are adding new states to the array. A single item has size 4 so in the labwc case it was 1 state (most likely `activated`) then 5 states (likely `activated` and the 4 tiled edges) then 1 state (back to only `activated`), whereas at gnome it was 1 state -> 4 states -> 1 state.

If you feel like spending some more time on this you could use an old toy project of mine that I used to learn about the wayland wire protocol instead of `WAYLAND_DEBUG=1`, that one doesn't parse arrays either but at least gives its content: https://github.com/Consolatis/wl_tee/

It can be called like `WL_DEBUG_FILTER=xdg_toplevel.configure ./wl_debug.sh tilix`

**Comment by jp7677** [comment] 2024-02-26 19:33
PS: the only thing that got my attention in the gnome logs where `gtk_surface1@40.configure_edges(array[16])`, but don’t know if that is related.

**Comment by jp7677** [comment] 2024-02-26 19:44
Based on https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gdk/wayland/protocol/gtk-shell.xml?ref_type=heads#L55 I guess looks indeed like that.

**Comment by Consolatis** [comment] 2024-02-26 19:51
Side note:

Wlroots used to have an internal workaround in that if a client didn't support tiling notifications wlroots just sent a fake maximized state (that for the most part has the same effect as tiled on all edges but may have subtle differences like showing an un-maximize button in the CSD). But AFAIR they removed that workaround and left it up to the compositors to either do the same or don't fake it.

This would not solve this issue though because here GTK claims to support the tiling notifications but apparently does not implement it correctly based on the evidence I saw so far.

**Comment by jp7677** [comment] 2024-02-26 20:21
Hi @emilio , sorry for pinging you directly, but since you wrote https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6629 with other compositors than mutter in mind (well, according to the PR description) this might be interesting for you.

**Comment by emilio** [comment] 2024-02-27 12:54
Sure, I can try to take a poke, I can repro this.

**Comment by emilio** [comment] 2024-02-27 14:36
https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6952 is the fix for this. Ironically a related fix (https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6742) which also affects gtk4 (https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6745) would've papered over this issue.

**Comment by jp7677** [comment] 2024-02-27 16:15
Thanks a lot for directly addressing this, very cool!

**Comment by Consolatis** [comment] 2024-02-27 21:44
@emilio great. Thanks!

**Closed** 2024-02-27 21:45 UTC
Labels: help wanted, investigation required, UX

**Comment by jp7677** [comment] 2024-05-26 11:52
GTK3 3.24.42 has been released recently and with this version the corners return nicely rounded when un-tiling. 

Now we just need the SSD corners to show (conditionally) the same behavior and  all is beautiful consistent.
