### ISSUE TITLE
Feature Request: Tablet Relative Tracking Mode

### ISSUE THREAD

**Issue by justin330** [labwc/labwc#1957] opened 2024-07-03 13:24 UTC
I'd noticed the recent addition of mouseEmulation since updating, and got my hopes up that relative tracking support had finally  been added to labwc, but to my disappointment it seems to be for pen pressure only?

I used relative tracking extensively on Xorg desktops because it is much easier to write with when using my 'signature' sized Wacom tablet. I'd really appreciate if such a feature could be added if its not too much trouble.

**Comment by jp7677** [comment] 2024-07-03 20:07
Well, sorry to having you disappointed ;)

If you are able to compile labwc, you might try this PR https://github.com/labwc/labwc/pull/1962

For relative motion, you'll also need this configuration option:

```xml
    <tablet motion="relative" />
```

Note that this configuration switch will very likely change.

**Comment by justin330** [comment] 2024-07-03 20:53
Wow, that was fast! Thank you!
I just tried it out and it mostly works; but there is a diagonal drift that occurs whenever there is motion.

**Comment by justin330** [comment] 2024-07-03 20:59
I just tried a couple things and it seems to occur when the rotation is changed

**Comment by jp7677** [comment] 2024-07-03 21:00
Thanks for the fast feedback :). Could you explain a bit more detailed what you mean by diagonal drift and what motion is needed (eg. straight or also diagonal). Is this always like this (eg desktop vs surface). Do you have other tablet settings set?

**Comment by justin330** [comment] 2024-07-03 21:10
The drift also seems to occur whenever there is an motion event, such as when the x, y, or proximity to the pad changes.

**Comment by justin330** [comment] 2024-07-03 21:17
Another request if I may? Would you be able to add an entry to change the speed of the pen while in relative mode?

**Comment by jp7677** [comment] 2024-07-04 05:07
> I just tried a couple things and it seems to occur when the rotation is changed from 0

Thanks for the hint, the "drift" should be gone now i.c.w. rotation.

**Comment by justin330** [comment] 2024-07-04 12:55
Thank you so much for your speedy work! 

The drift is now gone while the pen is within the pad's workable area, though if the pen is moved outside the workable
area there is a drift in that direction. 

To be honest, though unintended its kind of nice in a way, its a bit the auto-scroll when dragging selected files to the top or bottom of the list in a file manager.

Here's a brief illustration:
* Orange is the tablet's workable area, corresponding to the white lines on the tablet
![diagram](https://github.com/labwc/labwc/assets/9954903/171cda39-cf17-494d-a355-b45da5e3b91a)

**Comment by jp7677** [comment] 2024-07-04 13:16
> Thank you so much for your speedy work!

You are welcome!

> The drift is now completely gone while the pen is within the pad's workable area, though if the pen is moved outside the workable area there is a drift in that direction.

Interesting. Does that happens all the time or just with rotation set to anything other than 0?

**Comment by justin330** [comment] 2024-07-04 15:17
Sorry for the late reply. Yes it happens on all rotation modes.

**Comment by jp7677** [comment] 2024-07-04 15:43
> Sorry for the late reply. Yes it happens on all rotation modes.
> 
> While I'm completely fine with it as is, as the pen is not intended to be tracked outside the working area anyway, I thought I should mention it regardless.

Thanks, could you please retry? The drifting on the edges should be gone now too. Contrary to absolute coordinates, there is no need to remember relative coords.

**Comment by justin330** [comment] 2024-07-04 15:55
Yes it is completely fixed now, great work!

**Comment by jp7677** [comment] 2024-07-05 05:01
> > Another request if I may? Would you be able to add an entry to change the speed of the pen while in relative mode? Thank you regardless.
> 
> I was already afraid that something like this is also needed. Will take a look ;)

With the latest version, the configuration looks slightly different now in preparation of multiple tool configs. The `motion` option move to a new `tabletTool` node and `relativeMotionSensitivity` allows you to adjust the speed. `1.0` is the original speed, `0.5` is 50% slower and `2.0` would be twice as fast etc. Any positive number is valid. 

```xml
  <tablet rotate="0" />
  <tabletTool motion="relative" relativeMotionSensitivity="0.5" />
```

Let me know if this works for you.
(Everything is still draft though, so nothing is set in stone)

**Comment by justin330** [comment] 2024-07-05 10:05
I just tried the latest version, the with the config  `<tabletTool motion="relative" relativeMotionSensitivity="1"/>` it works exactly as I needed it, thank you so much for this.

**Comment by jp7677** [comment] 2024-07-05 10:52
> I just tried the latest version, the with the config `<tabletTool motion="relative" relativeMotionSensitivity="1"/>` it works exactly as I needed it, thank you so much for this.

Cool to read that, thanks! Out of curiosity, `relativeMotionSensitivity="1"` shouldn't change anything compared to before I added that option. Only values other than `1` should show a difference. Do you see different behavior?

PS: Could you please reopen that issue until the PR is merged. That makes tracking easier in case others are looking for this feature.

**Comment by justin330** [comment] 2024-07-05 14:51
Sure, sorry about that.

Yeah, values other than 1 change the sensitivity as expected, even decimal values work. I should have explicitly mentioned that at the time.

Everything works as expected, though now I'm noticing a really annoying problem with libinput's own smoothing, but that is a problem with libinput and not labwc. (https://gitlab.freedesktop.org/libinput/libinput/-/issues/225)

Just to illustrate what I mean; when moving then lifting the pen and returning it to the original spot too quickly the cursor will warp back to the original spot. Though I'll be looking into trying to address this myself for the time being, even if it requires a hacky solution.

Once again thank you for adding this feature.

**Comment by justin330** [comment] 2024-07-05 15:03
I don't wish to nag, but I've just noticed one more thing; the relative tracking seems to be using a non-flat acceleration profile doesn't it? I was wondering why it felt a bit off. Is that an option that can be configured as well? If so I believe that would just about complete things.

**Comment by jp7677** [comment] 2024-07-05 19:58
> I don't wish to nag, but I've just noticed one more thing; the relative tracking seems to be using a non-flat acceleration profile doesn't it? As it seemed a bit off regardless of whichever sensitivity I used...
> 
> Is that an option that can be configured as well? If so I believe that would just about complete things.

No worries, I really appreciate the thorough testing and feedback. Please continue to post what you see.

Could you please describe what you mean with non-flat acceleration profile? I added the sensitivity in the most simple way, just taking the delta x,y from wlroots/libinput and multiply those value by the sensitivity. See https://github.com/labwc/labwc/blob/042805bb64a05389d9ad159e45d1ac0e0a34d1c4/src/input/tablet.c#L120-L124

When I'm moving the stylus from left to right with the same speed (as far as my hand allow), I don't see any (visible) speed increase of the cursor. But I'm not sure if that is what your question is about.

**Comment by droc12345** [comment] 2024-07-05 20:46
acceleration is usually done by libinput

> Accel profiles:   flat *adaptive custom

**Comment by justin330** [comment] 2024-07-05 20:47
Try this to see if you witness the same thing:

- open a drawing program
- place a card or ruler firmly against the middle of your tablet
- trace a line
- then do a "C" motion against the card

Under a flat acceleration profile regardless of the sensitivity, the cursor should always arrive at the contour of the ruler/card.

Here is a video demonstration:
[2024-07-05 21-36-25 87_q35.mkv.webm](https://github.com/labwc/labwc/assets/9954903/70b52862-7126-4a04-934f-77123b084d80)

**Comment by jp7677** [comment] 2024-07-05 21:36
Thanks a lot. I can reproduce, albeit this effect is more subtle on my setup. Since this also happens with sensitivity set to `1`, this is at least not a result of my cheap sensitivity algorithm. I guess now is the moment to dig into `libinput` to understand what those reported deltas are. Do you see the same effect in Sway?

**Comment by justin330** [comment] 2024-07-05 22:12
What configs do I need to add to Sway to get the tablet into relative tracking?

**Comment by jp7677** [comment] 2024-07-06 04:17
> What configs do I need to add to Sway to get the tablet into relative tracking?

https://man.archlinux.org/man/sway-input.5#TABLET_CONFIGURATION

**Comment by justin330** [comment] 2024-07-06 10:05
While I couldn't figure out how to set it up in Sway (I don't use those kinds of desktops, nor could I find any example configs to go from), I tested in Gnome too, in both Wayland, Xorg, I also tested it in xfce(Xorg); the issue is present in Gnome too on my end, so very likely all Wayland desktops that offer relative tablet tracking will have this issue, however in X, which uses xf86-input-wacom the issue is not present.

So it is certainly coming from the libinput side of things, does libinput not expose a method for changing the acceleration profile for tablets while in relative tracking mode, similar to how it is done for the mouse?

**Comment by justin330** [comment] 2024-07-06 10:48
I found the cause of it.

If you build the release libinput 1.26.1 with this patch (from https://gist.github.com/tadeokondrak/d4bd1aeacb399127ec69de45b2b202ad) :

```
--- evdev-tablet.c	2024-06-27 03:48:55.000000000 +0100
+++ evdev-tablet.c	2024-07-06 11:40:52.031182600 +0100
@@ -744,7 +744,7 @@
 	}
 
 	tablet_history_push(tablet, &tablet->axes);
-	tablet_smoothen_axes(tablet, &axes);
+	// tablet_smoothen_axes(tablet, &axes);
 
 	/* The delta relies on the last *smooth* point, so we do it last */
 	axes.delta = tablet_tool_process_delta(tablet, tool, device, &axes, time);
```

This drift is removed, seems its not a part of acceleration at all but the poor smoothing method they employ.

https://gitlab.freedesktop.org/libinput/libinput/-/releases
https://wayland.freedesktop.org/libinput/doc/latest/building.html

**Comment by droc12345** [comment] 2024-07-06 10:49
libinput can be confiigured to have wacom, but that depends on how the distro compiles it.
Not sure if the end user can configure what's installed though.

**Comment by jp7677** [comment] 2024-07-06 11:02
> I found the cause of it.

Nice find, very cool to have an explanation for this behavior! I assume with this patch applied it's also fine when using the sensitivity setting from the labwc PR with a value other than 1?

I guess it is wise to open an issue on the libinput side about this. Considering the difference to x11, this looks like a valid case to at least consider to make the tablet axes smoothing configurable.

**Comment by droc12345** [comment] 2024-07-06 11:07
comment for axis smoothing

>    Taking the tablet events as-is produces the occasional wobble in what should
    be a straight line. Bug 99961 has a jpg attachment to illustrate that.
    Emulate the wacom driver behavior and average x/y across the last 4 values to
    smoothen out these dents.

**Comment by droc12345** [comment] 2024-07-06 12:01
I'm having a hard time following through the code but have you tried the AttrTabletSmoothing quirk.
I'm just unsure what effect this really has.

`AttrTabletSmoothing=1|0`

`    Enables (1) or disables (0) input smoothing for tablet devices. Smoothing is enabled by default, except on AES devices`

**Comment by justin330** [comment] 2024-07-06 13:20
I can confirm adding 
```
[Wacom Unsmooth]
MatchName=Wacom*
AttrTabletSmoothing=0
```
to `/etc/libinput/local-overrides.quirks` with the system-provided libinput also fixes this, nice find!

**Comment by droc12345** [comment] 2024-07-06 13:43
Maybe something here https://wayland.freedesktop.org/libinput/doc/latest/tablet-support.html

**Comment by justin330** [comment] 2024-07-06 13:55
Unfortunately, there seems to be no mention of lowering the distance/proximity threshold on the docs link, and my searches aren't finding anything either. 

That quirks file is interesting though, is there any way I can obtain all the available quirks I could try out?

**Comment by droc12345** [comment] 2024-07-08 09:57
>For example, the Wacom mouse and lens cursor tools are usually used in relative mode, lying flat on the tablet. Movement typically follows the interaction normal mouse movements have, i.e. slightly lift the tool and place it in a separate location. The proximity detection on Wacom tablets however extends further than the user may lift the mouse, i.e. the tool may not be lifted out of physical proximity. For such tools, libinput provides software-emulated proximity.

I don't think you can do anything about proximity, and I couldn't find anything about software-emulated proxmiity outside of the comment above. Maybe it's activated automatically. 

The link above about tablet-support has all libinput info about tablets.

**Closed** 2024-07-19 21:45 UTC
