### ISSUE TITLE
Window resizing bug

### ISSUE THREAD

**Issue by oifj34f34f** [labwc/labwc#964] opened 2023-06-26 18:04 UTC
## Description

Sometimes when you resize a window in labwc (via Alt + Right mouse button), the window continues resizing after you release the mouse button

## Demo

[recording.webm](https://github.com/labwc/labwc/assets/128177553/b6d6f262-9016-45c0-ba5e-bb328fb1b4c0)

_In the video the right mouse button is released_

**Comment by johanmalm** [comment] 2023-06-26 18:32
Wow. That's a new one on me.
Could you describe your setup?
Are you running on a particularly slow machine or under heavy load? Or in a virtual box?
Could you replicate the same in sway? (use shift+super+space to put a window in floating mode)

**Comment by oifj34f34f** [comment] 2023-06-26 18:51
@johanmalm I tried labwc with the default configuration (updated the video in my first post), the problem remains. No, I have a pretty powerful pc, and there is no such problem in sway (I use it as my main wm). The problem can be reproduced by quickly resizing the window when switching windows (Alt + Tab).

**Comment by johanmalm** [comment] 2023-06-26 19:18
I can reproduce starting the alt-tabbing whilst still resizing. Should be able to stop that.
It doesn't carry on when I release the mouse button though.
Can you reproduce the resizing after releasing the mouse button if you just drag a corner rather than alt + right-press?

**Comment by oifj34f34f** [comment] 2023-06-26 19:25
Yeah, I just tried it (at the end of the video)

[recording.webm](https://github.com/labwc/labwc/assets/128177553/7a8311a0-07a9-442b-80d0-4340cecb3a32)

**Comment by johanmalm** [comment] 2023-06-26 19:29
That looks like you're doing the alt + right button though...??

If so, is it when you release alt button or the right-mouse-button that the window carries on resizing.

Also, is it intermittent? Looks like you had to try a few times for it to start misbehaving.

**Comment by oifj34f34f** [comment] 2023-06-26 19:34
@johanmalm I use Alt + right button, then move the cursor and immediately release the right button, and see if there is a bug. Yes, it doesn't always happen, only when the right button is pressed very quickly (with alt on).

**Comment by Consolatis** [comment] 2023-06-26 19:53
Yep, that looks like a bug here:
https://github.com/labwc/labwc/blob/c17bf6817619e2aa12baa54230081be35c5b46b0/src/cursor.c#L945-L969

We are supposed to end the interactive resize on button release (at the bottom of the code block). But we don't come there because the first condition matches (release on different surface) which then returns.

**Comment by Consolatis** [comment] 2023-09-14 12:02
This actually seems like a duplicate of #1053 (or rather that one being a duplicate if this issue).
It should be fixed by
- #1056 

Feel free to comment if its still an issue on latest master.

**Closed by Consolatis** 2023-09-14 12:02 UTC
