### ISSUE TITLE
Cursor disappears in Wine games

### ISSUE THREAD

**Issue by acoolstraw** [labwc/labwc#339] opened 2022-05-24 00:55 UTC
Cursor disappears in (seemingly) only Wine games when you click somewhere. The cursor stays where you clicked, but it doesn't move anymore, it's still functional though and reappears when alt tab out and back, then disappears again once you click on something.

Bug happens in Wreckfest, CS 1.6 and other Wine/Proton games. Interestingly, this bug doesn't happen if you have multiple displays/outputs. `WLR_NO_HARDWARE_CURSORS` doesn't make a difference.

**Comment by Relwi** [comment] 2022-08-29 21:21
It happens to me too, I only test with Steam games, in most games there is no issues with the cursor, but in some other games (Path of Exile, Guild Wars 2, Apex Legends) the cursor become invisible, the mouse actions works, but the cursor is invisible (only when playing at Fullscreen and Windowed Fullscreen).

**Comment by acoolstraw** [comment] 2022-10-10 02:21
Looking around in the ArchWiki, I found this. Could be a Wayland thing, not exclusive to labwc

https://wiki.archlinux.org/title/sway#Mouse_not_working_in_WINE_applications

**Comment by Ph42oN** [comment] 2022-10-12 19:48
I got this issue in Planetside 2. It only happens when i run it in fullscreen mode, not in windowed or windowed fullscreen. I tried looking at the code to find the cause. Commenting out this if in cursor.c in cursor_motion function makes mouse cursor move as expected:
`if (!seat->current_constraint) {`
So calling wlr_cursor_move even with constraints makes cursor work normally.

**Comment by FuzzyQuills** [comment] 2022-10-16 04:47
In my case, it seems the cursor doesn't vanish but gets stuck, yet moving the mouse itself around reveals that the actual cursor is still moving. (Overwatch 2)

Initially thought it was a GPU driver bug until I found this. Gamescope it is then.

**Comment by Consolatis** [comment] 2023-02-24 21:47
This should be fixed by #586.
If it isn't feel free to comment and we'll reopen this issue.

**Closed by Consolatis** 2023-02-24 21:47 UTC
Labels: bug, help wanted, investigation required
