### ISSUE TITLE
Copying/pasting from Wayland to Xwayland applications breaks sometimes

### ISSUE THREAD

**Issue by acoolstraw** [labwc/labwc#444] opened 2022-07-12 19:57 UTC
On master, and iirc on 0.5.x too, sometimes copying/pasting from Wayland to Xwayland applications and vice versa is broken. An example is Chromium, becomes a huge nuissance.

Unsure what exactly causes this, as most of the time it works, but sometimes if I close Chromium or restart labwc (I believe the latter is what causes this), it does this.

**Comment by Consolatis** [comment] 2022-07-12 20:01
Related:
- #166

**Comment by droc12345** [comment] 2022-07-17 20:47
I think it's a wlroots problem, though when I use wayfire it seems to not have problems.
I started noticing problems trying to c'n'p from wayland apps to xwayland apps (any of them)
you could try and paste and it wouldn't work. 

turned on debugging in labwc and this showed up (a lot)
[xwayland/selection/selection.c:148] not handling selection events: no seat assigned to xwayland
I'm guessing it has something to do with the problem even if it's not solely to blame.

**Comment by Consolatis** [comment] 2022-07-20 16:43
@droc12345 thanks a lot for the investigation. So if the issue is really that when restarting xwayland it doesn't get the proper seat assigned it could be worked around by having an X11 application active during the whole lifetime of labwc, something like `xcalc`.

Obviously this is not a satisfactory solution but would help in verifying that a missing seat assignment is indeed the root cause.

**Comment by droc12345** [comment] 2022-07-20 17:22
yeah, some little X app, xcalc, xeyes would work.

I've actually modified the cmd line that xwayland gets, to remove the "-terminate 10" flag which leaves Xwayland always started.

Just an fyi, inside the shell script that strarts the compositors I set env vars for X, wayland, etc
one of which is
export WLR_XWAYLAND="/home/don/bin/Xwayland.sh"
Which tells wlroots to start my script instead of the Xwayland binary, 
then inside that script, I modify the cmd line as needed, I want auth so I added that.
================
#!/bin/sh

authfile=$HOME/.Xauthority 
echo "$@" >>/tmp/xw.log
cmd=`echo "$@" | sed 's/ -terminate 10//'`

exec /usr/bin/Xwayland -dpi 163 -auth $authfile $cmd
=============

This is the default cmdline for wlroots to xwayland
:0 -rootless -core -terminate 10 -listenfd 28 -listenfd 29 -displayfd 74 -wm 71
where listenfd, displayfd and wm get set by what's available.

When terminate is left in the cmd, and xwayland dies (no X app running) when it gets restarted then
the listenfd fd's are kept, but new ones are applied to displayfd and wm. 

I have an issue opened at wlroots, https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3463
but no response yet.

**Comment by Consolatis** [comment] 2022-07-20 17:43
It would be nice if we could get to the root cause (which may or may not be in wlroots) so a restart re-assigns the correct seat.

But if preventing lazy start / restart fixes the issue I'd go for it for now until the seat issue is fixed. We should add a comment above that line though which clearly states why it has been changed to `false` and also links this issue and the wlroots one.

**Comment by droc12345** [comment] 2022-07-20 18:01
I just checked wayfire's code and they have lazy set to false, so that's why it's always there in wayfire.

Change to false, then test, but I haven't seen any problem with the terminate option removed, which  effectively does the same thing as not-lazy. The C'n'P works like it should. Just need those who are seeing problems on their end to try the "fix" and see what happens.

**Comment by Consolatis** [comment] 2022-07-21 01:10
PR pending:
- #457

Testing very much welcome.

**Comment by droc12345** [comment] 2022-07-21 09:35
Using the PR patch against the current git, xwayland gets started properly, or at least more properly than it was.
C'n'P works when X app is started, killed, xwayland allowed to die and restart with the next invocation of the X app. C'n'P  continues to work. From my viewpoint, it's solved.

**Closed** 2022-07-21 17:13 UTC
Labels: feedback required, PR pending
