### ISSUE TITLE
Xwayland doesn't work in fullscreen

### ISSUE THREAD

**Issue by jech** [labwc/labwc#2014] opened 2024-07-20 16:26 UTC
```
$ Xwayland :1 -fullscreen
XWAYLAND: wp_viewport@21: error 0: wl_viewport.set_destination sent with invalid values
(EE) could not connect to wayland server
```

**Comment by Consolatis** [comment] 2024-07-20 18:47
Is this on the labwc v0.7 branch (or one of its releases) or the current master branch?
At least on v0.7 It works fine for me nested (although with a rather old xwayland version 23.2.2)

Is there any output scaling involved and could you run it with `WAYLAND_DEBUG=1`?

**Comment by jech** [comment] 2024-07-20 20:01
> Is this on the labwc v0.7 branch (or one of its releases) or the current master branch?

It's the branch `consolatis/fix/magnifier_direct_scanout`, which is 0.7.3 plus 5 commits.  (I cannot currently run master because both libwayland-protocols and libdrm are too old.)

> Is there any output scaling involved

Not that I know of.

> could you run it with WAYLAND_DEBUG=1?

[xwayland.log](https://github.com/user-attachments/files/16322173/xwayland.log)

**Comment by Consolatis** [comment] 2024-07-20 21:03
Hm.. it looks like your Xwayland version indeed [violates](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/stable/viewporter/viewporter.xml#L166) the protocol by setting the destination size to 0:

```
[1132541.018] xdg_toplevel@18.configure(0, 0, array[0])
[1132541.029] xdg_surface@17.configure(109488)
[1132541.035]  -> xdg_toplevel@18.set_fullscreen(nil)
[1132541.040]  -> wp_viewport@21.set_source(0.00000000, 0.00000000, 640.00000000, 480.00000000)
[1132541.046]  -> wp_viewport@21.set_destination(0, 0)
[1132541.050]  -> wl_surface@16.commit()
[1132541.054]  -> xdg_surface@17.ack_configure(109488)
[1132541.057]  -> wl_surface@16.commit()
```

In comparison to the run of mine (Xwayland version 23.2.2):
```
[  89775.921] xdg_toplevel@16.configure(0, 0, array[0])
[  89775.936] xdg_surface@15.configure(272)
[  89775.953]  -> xdg_toplevel@16.set_fullscreen(wl_output@13)
[  89775.974]  -> wp_viewport@19.set_source(0.00000000, 0.00000000, 640.00000000, 480.00000000)
[  89775.990]  -> wp_viewport@19.set_destination(1280, 720)
[  89776.005]  -> wl_surface@3.commit()
[  89776.018]  -> xdg_surface@15.ack_configure(272)
[  89776.030]  -> wl_surface@3.commit()
```

I have no idea why Xwayland is doing that though. What does `Xwayland -version` say?

**Comment by jech** [comment] 2024-07-20 21:41
> What does `Xwayland -version` say?

```
$ Xwayland -version
The X.Org Foundation Xwayland Version 24.1.0 (12401000)
X Protocol Version 11, Revision 0
```

**Comment by Consolatis** [comment] 2024-07-20 21:55
Then this looks like a xwayland regression so closing for now. If it ends up that labwc is doing something wrong we can always reopen but Xwayland should under no circumstances violate the protocol by using `set_destination(0, 0)`.

**Closed by Consolatis** 2024-07-20 21:55 UTC

**Comment by jech** [comment] 2024-07-20 22:01
Thanks.  Reported at https://gitlab.freedesktop.org/xorg/xserver/-/issues/1717.

**Comment by jech** [comment] 2024-07-24 13:47
Reportedly fixed by https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/1621

**Comment by Consolatis** [comment] 2024-07-24 14:22
Based on information from the bug report above, a workaround for anybody also running into this issue is to define the output manually via `-output`.
