### ISSUE TITLE
LabWC and Sway crashes if you run PyGame a lot of times and turn it off.

### ISSUE THREAD

**Issue by IntinteDAO** [labwc/labwc#1743] opened 2024-04-21 11:29 UTC
I suspect it's a problem with WlRoots, but the recommended path is by writing to the project that uses it. 

But I don't know how to get the logs either.

Running PyGame code (and shutting it down) causes LabWC and Sway to shut down, i.e. the logging manager starts up. There seems to be a crash for some reason.

I made a simple code that, when run, leads to this situation

```
#!/usr/bin/python3

import pygame

ekran_szerokosc = 800
ekran_wysokosc = 600

while True:
    pygame.init()
    ekran = pygame.display.set_mode((ekran_szerokosc, ekran_wysokosc))
    pygame.quit()
```

OS: Debian Trixie (Testing)
Labwc: 0.7.0-3
Wlroots: 0.17.1-2

**Comment by Consolatis** [comment] 2024-04-21 11:50
Can't reproduce with pygame `2.1.2+dfsg-5+b1` (bookworm) nor with `2.5.2-1.1` (testing).
Labwc: master branch
Wlroots: 0.17.2

However, I could reproduce it with `wlroots 0.17.1` and labwc `0.7.0`.
Failed to reproduce with `wlroots 0.17.2` and labwc `0.7.0`.

So this looks like it has been fixed with wlroots `0.17.2` but Debian currently prevents that from getting merged into testing due to some ongoing transitions: https://tracker.debian.org/pkg/wlroots (same for labwc `0.7.1` and likely the upcoming labwc `0.7.2` btw).

wlroots `0.17.2` is available via `sid` though.

**Closed by Consolatis** 2024-04-21 11:50 UTC
