### ISSUE TITLE
when toggling fullscreen for terminal (foot) it loses focus

### ISSUE THREAD

**Issue by sidesteps** [labwc/labwc#2468] opened 2024-12-30 20:06 UTC
### Problem description

When toggling fullscreen for terminal it loses focus, so you have to click on the terminal window first to start typing on it.
I'm using

```
<keybind key="F11">
        <action name="ToggleFullscreen"/>
 </keybind>
```

### Steps to reproduce

Define above keymap
open foot terminal
press F11
terminal is in full screen but focus is lost - can't type commands
click on terminal window with a mouse
now you can type

### labwc build source

Release

### labwc version

0.8.2

### labwc environment

From a TTY or some display manager like lightdm

### Distribution

Arch Linux

**Comment by Narrat** [comment] 2024-12-30 21:15
Same setup and this keybind is working fine for me.
Maybe post your complete config, or at least the keybinds? You could also try if this happens with the default config + this keybind added

**Comment by sidesteps** [comment] 2024-12-31 13:05
This seem to happen when running labwc as xfces' window manager with `startxfce4 --wayland`

It works fine when labwc is started from tty.
So looks like xfce and labwc doesn't play nice here.

**Comment by Consolatis** [comment] 2024-12-31 13:37
Hm.. I wonder if this is related to xfce4panel. Maybe it reacts to the fullscreen state in some way that requests keyboard focus.

**Comment by sidesteps** [comment] 2024-12-31 15:01
Yes it's xfce4panel: https://gitlab.xfce.org/xfce/xfce4-panel/-/issues/894#note_99264

**Comment by Consolatis** [comment] 2024-12-31 15:25
Thanks for the report and link. I'll close this issue as not a being caused by labwc directly.

For reference from the linked issue:
> This is because external plugins are remapped when a window goes to full screen. You can avoid this by forcing plugins to be internal with this command:
>> xfconf-query -c xfce4-panel -p /force-all-internal -s true -t bool --create

**Closed by Consolatis** 2024-12-31 15:25 UTC
Labels: bug

**Comment by sidesteps** [comment] 2024-12-31 16:51
My pleasure, thanks for taking a look!
