### ISSUE TITLE
Errors when switching windows while using blender (blender loses input on viewport)

### ISSUE THREAD

**Issue by charbelnicolas** [labwc/labwc#1507] opened 2024-02-06 05:17 UTC
When using blender and switching focus from the blender window to another window I sometimes get xcb errors... I don't know if this is related to a bug which makes blender unable to receive any input from the mouse on the current viewport after switching a window with the window switcher. Apparently this happens on SwayWM too per the blender issue tracker.

[https://projects.blender.org/blender/blender/issues/117225#issuecomment-1114837](https://projects.blender.org/blender/blender/issues/117225#issuecomment-1114837)

Here's the screenshot of the errors I get while using blender:

![ss_2024_02_03_17_32_48](https://github.com/labwc/labwc/assets/14960414/37308058-044b-490f-b809-32dad229034c)

I tried Hyprland today using similar shortcuts and didn't have any problems at all with blender so there must be something going on with labwc...

_Originally posted by @charbelnicolas in https://github.com/labwc/labwc/discussions/1502_

**Comment by charbelnicolas** [comment] 2024-02-06 16:54
This happens to me mostly when switching windows from chromium to blender... Chromium uses xwayland still and blender is wayland native.

**Comment by Consolatis** [comment] 2024-02-06 19:32
Based on the linked bug report from blender it seems to bail out in some capacity if the keystate after a receiving focus is not consistent with blender's internal xkb state:

`WARN (ghost.wl.keyboard.depressed): intern/ghost/intern/GHOST_SystemWayland.cc:7079 getModifierKeys: modifier (OS) state is inconsistent (GHOST held keys do not match XKB)`

The xcb errors can be related but don't have to. Do you get the same issue when running blender wayland native (it showing up with `[xdg-shell]` in `A-Tab`)? That would eliminate xwayland as potential contributor the the issue.

**Comment by charbelnicolas** [comment] 2024-02-06 20:07
Yes, this happens when running blender in wayland ([xdg-shell])...

I also got these errors when trying to reproduce the bug:

```
02:55:18.911 [ERROR] [../labwc/src/view.c:980] view has no output, not updating geometry
02:55:18.911 [ERROR] [../labwc/src/view.c:626] view has no output, not positioning
```

```
03:08:54.437 [ERROR] [xwayland/xwm.c:1599] xcb error: op ChangeProperty (no minor), code Window (no extension), sequence 8017, value 14680065
03:08:54.437 [ERROR] [xwayland/xwm.c:1599] xcb error: op ChangeProperty (no minor), code Window (no extension), sequence 8019, value 14680065
03:08:54.437 [ERROR] [xwayland/xwm.c:1599] xcb error: op DeleteProperty (no minor), code Window (no extension), sequence 8020, value 14680065
```

```
03:13:58.432 [ERROR] [xwayland/xwm.c:1599] xcb error: op ChangeWindowAttributes (no minor), code Window (no extension), sequence 1850, value 14680538
03:13:58.432 [ERROR] [xwayland/xwm.c:1599] xcb error: op SendEvent (no minor), code Window (no extension), sequence 1851, value 14680538
```

And yes, this is the error that blender throws when run from the terminal:

```
WARN (ghost.wl.keyboard.depressed): intern/ghost/intern/GHOST_SystemWayland.cc:6079 getModifierKeys: modifier (OS) state is inconsistent (GHOST held keys do not match XKB)
```

I think it only happens when switching from [xwayland] apps directly into wayland [xdg-shell] blender... I haven't seen it happen when xwayland is not involved.

There is an easy workaround but very annoying, you only have to press the SUPER key one more time and then the problem goes away (in this case I use SUPER + TAB for the window switcher, not ALT-TAB)

**Comment by Consolatis** [comment] 2024-02-06 20:16
The `view has no output` errors should actually not be errors in the first place but rather debug logs, they can happen when the screen is turned off and similar situations. The `xwm.c` errors are completely unrelated, those can only be triggered by xwayland applications.

> I think it only happens when switching from [xwayland] apps directly into wayland [xdg-shell] blender... I haven't seen it happen when xwayland is not involved.

This might be a good hint for further debugging. CC @johanmalm @jlindgren90 as they know the keystate handling best.

**Comment by charbelnicolas** [comment] 2024-02-06 20:31
Never mind what I said earlier about xwayland apps being the only ones that trigger this bug. I tried again using pure wayland chromium [xdg-shell] and I still get the same error when switching windows... The good thing is it doesn't happen as often....

I do get lots of errors though when switching windows around (using chromium and blender):

```
03:31:00.018 [ERROR] [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x5e6636d50030
03:31:00.853 [ERROR] [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x5e6636d50030
03:31:59.914 [ERROR] [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x5e6636dda080
03:32:08.184 [ERROR] [backend/drm/atomic.c:73] connector HDMI-A-1: Atomic commit failed: Device or resource busy
03:32:08.184 [ERROR] [../labwc/src/common/scene-helpers.c:58] Failed to commit output HDMI-A-1
03:32:08.201 [ERROR] [backend/drm/atomic.c:73] connector HDMI-A-1: Atomic commit failed: Device or resource busy
03:32:08.201 [ERROR] [../labwc/src/common/scene-helpers.c:58] Failed to commit output HDMI-A-1
03:32:08.217 [ERROR] [backend/drm/atomic.c:73] connector HDMI-A-1: Atomic commit failed: Device or resource busy
03:32:08.217 [ERROR] [../labwc/src/common/scene-helpers.c:58] Failed to commit output HDMI-A-1
03:32:08.234 [ERROR] [backend/drm/atomic.c:73] connector HDMI-A-1: Atomic commit failed: Device or resource busy
03:32:08.234 [ERROR] [../labwc/src/common/scene-helpers.c:58] Failed to commit output HDMI-A-1
03:32:08.251 [ERROR] [backend/drm/atomic.c:73] connector HDMI-A-1: Atomic commit failed: Device or resource busy
03:32:08.251 [ERROR] [../labwc/src/common/scene-helpers.c:58] Failed to commit output HDMI-A-1
03:32:08.267 [ERROR] [backend/drm/atomic.c:73] connector HDMI-A-1: Atomic commit failed: Device or resource busy
03:32:08.267 [ERROR] [../labwc/src/common/scene-helpers.c:58] Failed to commit output HDMI-A-1
03:32:13.762 [ERROR] [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x5e6636d1b410
03:32:15.890 [ERROR] [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x5e6636d1eaa0
```

Don't know if that has anything to do with it though...

**Comment by johanmalm** [comment] 2024-02-07 22:07
Broadcasting modifiers to all clients may solve this.

**Comment by charbelnicolas** [comment] 2024-04-29 23:46
Hello, sorry to bother you guys, any news on this? :)

**Comment by johanmalm** [comment] 2024-11-12 21:19
Could you write out some steps to reproduce - with expected results vs actual result.
I'll install `blender` to see if I can get my head around it.

**Comment by charbelnicolas** [comment] 2024-11-13 01:29
> Could you write out some steps to reproduce - with expected results vs actual result. I'll install `blender` to see if I can get my head around it.

Sure, next time I run into this bug I'll try to write down the steps to reproduce it and I'll report here. Thank you.

**Comment by charbelnicolas** [comment] 2024-11-13 02:26
I can reproduce it consistently now! It's really easy to trigger it. You only have to cycle through the window switcher once without actually changing the window.

Step 1. Open blender and focus the viewport.
Step 2. Press whatever keys you have set up to activate the OSD window switcher.
Step 3. Instead of changing to another window, select the blender window again after cycling through the whole window switcher list.
Step 4. Try to move the view on the viewport and it will not work unless you press the Super key again.

BTW, if I start to record a video with the following shortcut:

```
<keybind key="W-Print">
	<action name="Execute">
		<command>sh -c 'wf-recorder -ac libx264rgb -F fps=60 -f ~/Videos/vid_$(date +%Y_%m_%d)_$(date +%H_%M_%S).mp4'</command>
	</action>
</keybind>
```
Blender viewport loses input too...

Here's a video I recorded:

[https://drive.google.com/file/d/1sVyA6l3fmd1njJ7Lxo8rm8O6JqPkXhCW/view?usp=sharing](https://drive.google.com/file/d/1sVyA6l3fmd1njJ7Lxo8rm8O6JqPkXhCW/view?usp=sharing)

I hope we can finally get rid of this pesky little bug :)

**Comment by charbelnicolas** [comment] 2024-11-13 02:29
Everytime I use the Super key to launch, execute a command or do something when the blender window is focused it loses input focus until you press the Super key again.

**Comment by johanmalm** [comment] 2024-11-21 23:01
Sorry - blender noob here. How do you get the view to move around in blender to start with? Have tried to move cursor whilst holding ctrl/alt - but can't get it to work.

**Comment by charbelnicolas** [comment] 2024-11-21 23:34
> Sorry - blender noob here. How do you get the view to move around in blender to start with? Have tried to move cursor whilst holding ctrl/alt - but can't get it to work.

Hi Johan, if you click the `MMB` and drag the mouse you can rotate the view, if you hold `shift` + `MMB` you can pan the view.

**Comment by johanmalm** [comment] 2024-11-22 22:16
I've tried taking the described steps, but cannot reproduce. I can still rotate the view with `MMB` after alt-tabbing.

Questions:

1. You state "press the Super key again". It's not clear to me why you said "again" but it makes me thing this might be important. Do you use `Super` as part of the window-switcher keybind?
2. Have you tried on master? We introduced this (https://github.com/labwc/labwc/pull/2274) change recently which may help. I've been trying with both `0.8.1` and `master` and it works fine with both, but thought I'd mention it.
3. Do you still get the problem if you run without a config file (to force default settings). For example `labwc -C /dev/null`

**Comment by charbelnicolas** [comment] 2024-11-22 22:44
> I've tried taking the described steps, but cannot reproduce. I can still rotate the view with `MMB` after alt-tabbing.
> 
> Questions:
> 
> 1. You state "press the Super key again". It's not clear to me why you said "again" but it makes me thing this might be important. Do you use `Super` as part of the window-switcher keybind?
> 2. Have you tried on master? We introduced this ([keyboard: broadcast modifiers #2274](https://github.com/labwc/labwc/pull/2274)) change recently which may help. I've been trying with both `0.8.1` and `master` and it works fine with both, but thought I'd mention it.
> 3. Do you still get the problem if you run without a config file (to force default settings). For example `labwc -C /dev/null`

Hello Johan,

1. Yes, most of my keybinds involve the SUPER (windows key). I use SUPER + TAB to switch windows.
```
<keybind key="W-Tab">
	<action name="NextWindow" />		
</keybind>
```
2. Yes, I've been daily driving the master branch for the last couple of months.
3. I just checked using the default config and using ALT + TAB has the same issue, blender still behaves as if ALT were pressed when interacting with the viewport so it uses ALT as a modifier inside blender. If I press ALT again everything goes back to normal.

So the issue is that either SUPER or the ALT keys are being presented to blender as if they were still pressed? This only happens when cycling through the whole window switcher list without selecting another window other than blender.

I do this very often to check if blender's file is saved or not (it shows a * on the title name). I don't use a taskbar nor a titlebar. It's the easiest way for me to check the application's title without toggling any bars that would otherwise disrupt the view.

Thank you

**Comment by charbelnicolas** [comment] 2024-11-22 22:46
I'd suppose doing a reset on the modifier key state when using the window switcher if no actual window was switched out of view would work would it not?

**Comment by charbelnicolas** [comment] 2024-11-22 22:49
It is as if labwc is still waiting for a "switched view" kind of event to reset the pressed state on the modifier key

**Comment by johanmalm** [comment] 2024-11-23 13:24
Thanks. I can reproduce it now. The same thing actually happens with all keybinds.

See #2377 as a starting point. It's just a quick patch, but is hopefully a good starting point for thinking through how we best support this.

**Comment by charbelnicolas** [comment] 2024-11-23 15:18
> Thanks. I can reproduce it now. The same thing actually happens with all keybinds.

That's good to hear! Yes, when using a keybind to capture video it does the same thing, that's why have I always used the SUPER key for keybinds since no software uses it internally for modifiers. That's why it was odd to me to use ALT + TAB to switch windows and changed it on the very first day I used labwc.

> See #2377 as a starting point. It's just a quick patch, but is hopefully a good starting point for thinking through how we best support this.

Cool, thank you very much! I'm going to revise on how to do the patching since I've done it only one other time a few months ago (I usually just build using the last git commit)

**Comment by Consolatis** [comment] 2024-11-26 20:26
Should be fixed in the latest master branch and can be enabled with a window rule targeting blender which sets the [wantAbsorbedModifierReleaseEvents](https://labwc.github.io/labwc-config.5.html#entry_windowrules_windowrule_wantabsorbedmodifierreleaseevents=) property. Something like
```xml
<windowRules>
	<windowRule identifier="blender" wantAbsorbedModifierReleaseEvents="yes" />
</windowRules>
```

Please comment if this doesn't work.

---
Should we add this to the website FAQ section?

**Closed by Consolatis** 2024-11-26 20:26 UTC
Labels: bug, help wanted, investigation required

**Comment by charbelnicolas** [comment] 2024-11-27 14:48
It works pretty well! Thank you guys!
