### ISSUE TITLE
Some applications segfault if they aren't started with GDK_BACKEND=x11 environment variable

### ISSUE THREAD

**Issue by tprepper** [labwc/labwc#979] opened 2023-07-08 05:38 UTC
Unless you start certain applications (so far I've seen lxappearance-gtk3 and xfdesktop do this) with for example `GDK_BACKEND=x11 lxappearance`, they will segfault on launch

```
$ lxappearance 
Segmentation fault (core dumped)
```
```
$ xfdesktop
Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined

(xfdesktop:28359): Gdk-CRITICAL **: 08:37:39.940: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed

(xfdesktop:28359): Gdk-CRITICAL **: 08:37:39.940: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed
Segmentation fault (core dumped)
```

**Comment by tprepper** [comment] 2023-07-08 05:40
xfdesktop is primarily an X11 program (with experimental Wayland support it seems?) so it might be hardcoded

**Comment by tprepper** [comment] 2023-07-08 05:47
Same behavior on sway, probably the program itself's fault

**Comment by Consolatis** [comment] 2023-07-08 13:56
This is usually caused by the application using the GDK wayland backend as configured by the user but still trying to use some hardcoded X11 calls. Bug reports to those applications (after checking that it isn't already fixed in a later version and there isn't already a bug report for it) would help.

In either case its a generic application issue, not related to labwc.

**Closed by Consolatis** 2023-07-08 13:56 UTC
