### ISSUE TITLE
Cursor does not change when resizing a window

### ISSUE THREAD

**Issue by keshto** [labwc/labwc#246] opened 2022-02-18 21:53 UTC
When the window is being resized with the mouse brought to the border it does not change to a resize cursor. This is also the case when mouse is brought to the border. Desired outcome would be for the cursor to change to a resize cursor.

**Comment by Consolatis** [comment] 2022-02-18 21:55
I never had that issue. Do your mouse cursors change at all?

**Comment by johanmalm** [comment] 2022-02-18 21:58
What type of window is it (xwayland or xdg). If you alt-tab it'll tell you.
Is window decoration showing.
Are you running from tty or under x11?

**Comment by johanmalm** [comment] 2022-02-18 22:18
Would you be able to try running tinywl.c to see if that works?
https://gitlab.freedesktop.org/wlroots/wlroots/-/tree/master/tinywl

**Comment by johanmalm** [comment] 2022-02-18 22:24
See
https://github.com/labwc/labwc/issues/231
https://github.com/labwc/labwc/issues/150

**Comment by johanmalm** [comment] 2022-02-18 22:25
Does it work with `WLR_NO_HARDWARE_CURSORS=1 labwc`

**Comment by keshto** [comment] 2022-02-18 22:37
> Does it work with `WLR_NO_HARDWARE_CURSORS=1 labwc`

tried that earlier, no

> Would you be able to try running tinywl.c to see if that works?
https://gitlab.freedesktop.org/wlroots/wlroots/-/tree/master/tinywl

tinywl wouldn't compile for me with wlroots-git so tried 0.15.1 and yes it shows the resize cursors. I recompiled labwc with wlroots 0.15.1 instead of git and still no.

**Comment by 01micko** [comment] 2022-02-21 11:14
Have you tried another cursor theme?

**Comment by keshto** [comment] 2022-02-21 12:41
I see the resize cursor in tinywl etc. So, dont think that is it, but will give it a try and report back if it works.

**Comment by ryanlath** [comment] 2022-03-20 17:48
I'm also having this problem, eg no resize, handgrab cursors, etc.

Tried:
- labwc 0.5.0-75-g4ee9f35 / labwc 0.5.0-80-g0604233
- wlroots 0.15.1/0.16
- two different cursor themes
- WLR_NO_HARDWARE_CURSORS=1

`0:00:00.692 [ERROR] [types/output/cursor.c:223] Failed to get cursor display formats`

**Comment by johanmalm** [comment] 2022-05-30 18:07
@keshto @ryanlath would you mind checking if you still experience this issue with the latest master. We've had some changes to `desktop_node_and_view_at()` which might have resolved this.
If not fixed, would you mind posting your `rc.xml`, `autostart` and `environment` files.

**Comment by keshto** [comment] 2022-07-07 21:30
@johanmalm fresh install (0.5.2). No config. Still no

**Comment by Consolatis** [comment] 2022-07-07 23:34
I still can't reproduce this in any shape or form but maybe I don't understand the actual issue.

This is how it looks for me with SSD clients:
![swappy-20220708_013136](https://user-images.githubusercontent.com/35009135/177888280-b094433b-6601-4c61-b985-14606d5dce98.png)
Are we actually talking about CSD (Client Side Decoration) clients here?

**Comment by acoolstraw** [comment] 2022-07-08 00:11
yep, that doesn't happen for me. it's just a normal cursor using the default Adwaita cursor theme on Arch.

I like the aesthetic of this and thought it was intentional, feels smooth and all... a bit hard to tell when I'm able to resize it though

**Comment by Consolatis** [comment] 2022-07-12 18:22
Maybe we can try to figure out some differences between our setups:
- compiled with xwayland support? If not, is it fixed by compiling with xwayland support (`meson configure -Dxwayland=enabled build`)?
- using another scale than `1`? If not, is it fixed by using a scale of `1`?

**Comment by ryanlath** [comment] 2022-07-12 21:41
it's sort of a wlroots issue:  the names `wlr_xcursor_get_resize_name` returns are "[freedesktop](https://www.freedesktop.org/wiki/Specifications/cursor-spec/)" names, but not necessarily standard X names...
`cursor_set(&server->seat, wlr_xcursor_get_resize_name(resize_edges));`
You could replace it with something like this:
```
labwc_xcursor_get_resize_name(enum wlr_edges edges) {

	if (edges & WLR_EDGE_TOP) {
		if (edges & WLR_EDGE_RIGHT) {
			return "top_right_corner";
		} else if (edges & WLR_EDGE_LEFT) {
			return "top_left_corner";
		}
		return "top_side";
	} else if (edges & WLR_EDGE_BOTTOM) {
		if (edges & WLR_EDGE_RIGHT) {
			return "bottom_right_corner";
		} else if (edges & WLR_EDGE_LEFT) {
			return "bottom_left_corner";
		}
		return "bottom_side";
	} else if (edges & WLR_EDGE_RIGHT) {
		return "right_side";
	} else if (edges & WLR_EDGE_LEFT) {
		return "left_side";
	}

	return "gumby"; // dammit!
}
```

**Comment by Consolatis** [comment] 2022-07-12 22:19
So the reason this doesn't work for some is that they don't have a freedesktop cursor theme installed.
That sheds some light on this issue, @ryanlath thank you!

What makes this even stranger is that wlroots is actually [shipping default cursor images](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/include/xcursor/cursor_data.h#L540)  but they appear to be using the "standard X names".

**Closed** 2022-09-11 20:20 UTC
Labels: bug, PR pending
