### ISSUE TITLE
Damage issues with client side decorations and scale > 1

### ISSUE THREAD

**Issue by knm100** [labwc/labwc#1697] opened 2024-04-09 08:47 UTC
environment: vmware 17.5.1, arch+labwc 7.1
When scale is greater than 1 by kanshi,   there will be a flash on the right and bottom border of  chromium and filechoose.
it only appears on the half of the screen of right side, not on the left side.
on labwc 6.6, It didn't appear.

https://github.com/labwc/labwc/assets/166389780/cc145f28-efcd-46bb-986a-6ba0953c76ee

**Comment by knm100** [comment] 2024-04-09 08:52
[log.txt](https://github.com/labwc/labwc/files/14916062/log.txt)

**Comment by Consolatis** [comment] 2024-04-09 09:15
That seems to be an issue with the damage detection of client side decorations. We do have reports about issues with vmware in particular since we switched to wlroots 0.17.x. Do you run the latest wlroots patch release (0.17.2 currently)?

**Comment by tokyo4j** [comment] 2024-04-09 09:19
I have no clue, but launching chromium as a wayland client with `--enable-features=UseOzonePlatform --ozone-platform=wayland`, or using egl as its renderer with `--use-gl=egl` might fix the issue.

**Comment by knm100** [comment] 2024-04-09 09:33
> That seems to be an issue with the damage detection of client side decorations. We do have reports about issues with vmware in particular since we switched to wlroots 0.17.x. Do you run the latest wlroots patch release (0.17.2 currently)?

Yes, Labwc run on wlroots0.17.2
![swappy-20240409-173004](https://github.com/labwc/labwc/assets/166389780/30cf98ee-3e09-4cc0-8d95-3232a2b926ef)

**Comment by Consolatis** [comment] 2024-04-09 09:45
Well, this seems to be a wlroots / vmware (more specifically their virtualized GPU drivers) interaction issue (at least I never heard of this issue before). I don't think labwc can do much about it, you might be able to work around it by starting labwc with software rendering (`WLR_RENDERER=pixman labwc`) but it might come at a performance cost.

**Comment by knm100** [comment] 2024-04-09 10:09
> I have no clue, but launching chromium as a wayland client with `--enable-features=UseOzonePlatform --ozone-platform=wayland`, or using egl as its renderer with `--use-gl=egl` (maybe `--use-gl=desktop`?) might fix the issue.

I pretty sure that  chromium run on wayland, because i compiled the labwc wiht -Dxwayland=disabled.
I will try --use-gl=egl

**Comment by knm100** [comment] 2024-04-13 01:19
Confirm  that using ssd can fix it

**Comment by johanmalm** [comment] 2024-04-13 18:41
It might be caused by transparent drop-shadows. Do you still get it if you run `labwc` like this: `WLR_SCENE_DISABLE_VISIBILITY=1 labwc`

Ref:
- https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/docs/env_vars.md?ref_type=heads

**Comment by knm100** [comment] 2024-04-13 23:46
didn't take effect.  

> It might be caused by transparent drop-shadows. Do you still get it if you run `labwc` like this: `WLR_SCENE_DISABLE_VISIBILITY=1 labwc`
> 
> Ref:
> 
> * https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/docs/env_vars.md?ref_type=heads

didn't take effect.

**Comment by kode54** [comment] 2024-04-20 01:01
Reproduced on wlroots 0.17.2 running on bare metal, default EGL renderer, on Radeon RX 6700 XT using radeonsi via Mesa 24.0.5, specifically with GNOME Calculator. Client side decorations with soft shadows it is. They don't appear to be propagating damage of translucent pixels to underlying surfaces until those surfaces damage themselves directly.

**Comment by Consolatis** [comment] 2024-04-23 14:20
I can't currently debug this so help would be much appreciated.

It might be related to the early return in https://github.com/labwc/labwc/blob/master/src/common/scene-helpers.c#L60, so one could test if adding `wlr_damage_ring_rotate(&scene_output->damage_ring);` before the `return false;` fixes things (and doesn't break anything else).

There is some upstream discussion about this whole thing here in case somebody wants to dive deep into wlroots damage tracking internals: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4253

**Comment by vyivel** [comment] 2024-05-04 22:57
Fixed in wlroots: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4668

**Comment by Consolatis** [comment] 2024-05-04 23:58
Thanks for the fix. As this is a bug in wlroots 0.17.x and we can't work around it from the labwc side there is not much we can do here. Thus closing the issue.

@vyivel 
Any chance of marking the PR as backport in case there is a wlroots 0.17.4 at some point?

**Closed** 2024-05-04 23:58 UTC
Labels: bug, help wanted, investigation required
