### ISSUE TITLE
Show corresponding tasks for each monitor on task bar with Dual Monitors

### ISSUE THREAD

**Issue by boris3812** [labwc/labwc#744] opened 2023-01-31 18:15 UTC
labwc version 0.6.1 (thanks guys for adding last version in AUR, and it works finally with wlroots 0.16.1 from community )
so of course we have Archlinux 😉

Verified on next panels:
- sfwbar
- wf-panel (from wf-shell)
- waybar (wlr/taskbar module)
(because we need some tint2 for our desktop 😁 )

So what we have now, when we work with 2 monitors - some tasks are showing on the taskbar from the second monitor.
How to reproduce and understand it:
When we are opening  some app, for example  from menu LabWC open the thunar or nemo or firefox or xed or tilix or gmrun or telegram or any over ->  yes , we see that the task for this window is on the correct monitor , so where it was discovered,
**but**,
when we are moving this window to the second monitor - the task still remains in the first monitor on our panel where it was opened !
**and**,
only when 
**1.** we are maximizing this window in our first monitor, after that 
**2.** we are moving it to the second monitor, and at last 
**3.** on the second monitor we also are maximizing this window 
- just only in this case the task will be moved to our second monitor .

**Comment by johanmalm** [comment] 2023-01-31 21:40
Thanks for logging this issue.

Does this patch solve it? https://github.com/labwc/labwc/pull/745

**Comment by boris3812** [comment] 2023-01-31 21:56
so I have maked build , and i have :
labwc 0.6.1-1-g1995a33   ,  I understand this is with you lasst patch ...

the problem is also present , only difference what i see - is only with terminal VTE (tilix) when i'm writing something , only after that it goes to other output, for else apps windows are still on first output

wroots version in comunity is wlroots 0.16.1-2, if this is important

**Comment by johanmalm** [comment] 2023-01-31 22:08
When I opened a new application it sometimes showed in `waybar` on both outputs. I had never realised that this was wrong - but do now and the patch fixes it.

> **but**, when we are moving this window to the second monitor - the task still remains in the first monitor on our panel where it was opened ! 

I can't reproduce this. When I move a window, it always just appears in waybar on the output that the window is mostly on.

Would you be happy to do some fault finding and compile + test?
If so, I'd start by adding to fprintf()s  in view_discover_output() to get a feel for what's going on.
https://github.com/labwc/labwc/blob/1995a33df96b907a9a4ecd6580924d76e8720109/src/view.c#L783

You can use `%p` for pointers like so `fprintf(stderr, "%p\n", view->output);`
...and `%d` for cordinates like this: `fprintf(stderr, "%d, %d\n", view->x, view->y);`

**Comment by boris3812** [comment] 2023-01-31 22:21
may be it will be more clear what is happening, i hope )

https://filedn.com/lyCLU10bkY6FUrIxXH2IUHz/2023-02-01_00-15-53.mp4

**Comment by boris3812** [comment] 2023-01-31 22:24
so when window is maximized , after that it shows on right output. it was **sfwbar**, so here I don't have  to be showed like in waybar on both outputs what you have.

**Comment by boris3812** [comment] 2023-01-31 22:29
about finding and compile + test : no problem , if that means only to make build after git clone with new fixes )

**Comment by johanmalm** [comment] 2023-01-31 22:39
Thanks for video. That is helpful.
I have run out of time tonight. Will try to re-produce tomorrow.

**Comment by boris3812** [comment] 2023-02-01 00:02
So , I  have some update for description what is going on ( in the end of video you can see more examples with only one window , app "Azote" ) . And what conclusions we have:
1. When you are opening app on primary monitor output , and then move to second and maximize the window  - it appears on taskbar of second monitor (so if just only moving window without maximize  - does not work)
2. but, if I open app at the second out put, after that I move it to primary monitor - so there and with maximize it does not work , only after i move it again at first monitor, just move, and remove agin to this second - so in this case, aster maximize window it appears on correctly output.

So here you are new video :)
https://filedn.com/lyCLU10bkY6FUrIxXH2IUHz/2023-02-01_01-41-22.mp4

**Comment by Consolatis** [comment] 2023-02-01 03:04
We are still using our own detection for `output_enter`/`leave` signals from the pre-scene-graph 0.5 days.
`wlr_scene_buffer` provide signals for those that we could use instead for foreign-toplevel.

They will likely be removed in wlroots 0.17 though, but wlroots provide a replacement:
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3879

**Comment by boris3812** [comment] 2023-02-01 16:43
and i forgot to mention, about workspaces. is the same question with tasks on taskbar. When I go to the next workspace on labwc desktop, on taskbar i see my tasks from the previous workspace, not current workspace only. i thought it was something in labwc to configure or to implement/fix, because here we are using "our" kind of workwspaces, just like on openbox ... so i understand this is again question for wlroots ? ...🤔  
so now what we have ? to see someday that the task are showed per output and per workspaces, when you move the window , we must wait some changes in wlroots 17 , or may be 18 , so after that they will be added in labwc ?

**Comment by Consolatis** [comment] 2023-02-02 12:00
> `wlr_scene_buffer` provides signals for those that we could use instead for foreign-toplevel.

Turns out we can't really use that for foreign-toplevel but PR #747  should solve all issues related to output tracking for panels.

> and i forgot to mention, about workspaces.

As long as the [ext-workspace protocol](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/40) is not merged there is no way for a panel to track workspaces in labwc.

**Comment by boris3812** [comment] 2023-02-02 12:54
> Turns out we can't really use that for foreign-toplevel but PR #747 should solve all issues related to output tracking for panels.
So i have been maded those 3 files, and look what we have. It feels of course better , but ... :)  

https://filedn.com/lyCLU10bkY6FUrIxXH2IUHz/2023-02-02_14-50-53.mp4

**Comment by Consolatis** [comment] 2023-02-02 13:03
Would you mind testing with a clean build?
```
git clone https://github.com/Consolatis/labwc.git
cd labwc
git checkout feature/foreign_output_tracking
meson setup build
meson compile -C build
```

and then test build/labwc

**Comment by boris3812** [comment] 2023-02-02 13:05
yes , lets try

**Comment by boris3812** [comment] 2023-02-02 13:13
https://filedn.com/lyCLU10bkY6FUrIxXH2IUHz/2023-02-02_15-10-47.mp4

**Comment by Consolatis** [comment] 2023-02-02 13:32
Hm.. can reproduce with sfwbar. Will debug this a bit further.

**Comment by boris3812** [comment] 2023-02-02 13:48
![Screenshot-20230202-154509](https://user-images.githubusercontent.com/93073422/216341887-3f3cb879-f827-43a1-8801-f2ff2b0a2aa4.png)

so here , after i was opening tilix on default output. after that we see nemo at second output

**Comment by Consolatis** [comment] 2023-02-02 13:59
`WAYLAND_DEBUG=1 /home/user/dev/sfwbar/build/sfwbar -m WL-2 --config ~/.config/sfwbar/own_bottom.config 2>&1 | grep 'toplevel.*output_` shows the correct events for me though, just as the window crosses the screen boundary.

**Comment by boris3812** [comment] 2023-02-02 14:16
Perhaps, i'm missing somethig ....
https://filedn.com/lyCLU10bkY6FUrIxXH2IUHz/2023-02-02_16-10-36.mp4

**Comment by Consolatis** [comment] 2023-02-02 14:26
The events in your latest video look fine. Both panels will always receive the same events but they should filter based on the id (the `@13`/`@16` part). The question is why they are not doing that and if its our / wlroots fault or if sfwbar does something wrong here.

**Comment by boris3812** [comment] 2023-02-02 20:42
so now it remains at both outputs. I have tried with and without environment WLR_WL_OUTPUTS=2 and    <snapping><range>0</range> .... or 1 in  ~/.config/labwc/rc.xml
and thats what we have at the moment....

https://filedn.com/lyCLU10bkY6FUrIxXH2IUHz/2023-02-02_22-33-09.mp4

**Comment by boris3812** [comment] 2023-02-02 21:14
and yes , i confirm that waybar works fine with moving window between outputs. and now our journey is
 with sfwbar only ... 🤔

**Comment by boris3812** [comment] 2023-02-03 03:40
> The diff in https://github.com/LBCrion/sfwbar/issues/74 should fix it for sfwbar.


Now yes, the last diff fix it for sfwbar )

Thanks!

**Comment by Consolatis** [comment] 2023-02-03 04:37
Awesome. Thanks for testing and bringing this up in the first place :)

Will leave this issue open until we merge
- #747

**Closed** 2023-02-03 21:59 UTC
Labels: enhancement, PR pending
