### ISSUE TITLE
Regression - video blocks in fullscreen with firefox

### ISSUE THREAD

**Issue by stefonarch** [labwc/labwc#1273] opened 2023-12-02 21:17 UTC
As title, it recovers only when moving the cursor or a notification popup appears. In falkon and chromium (which runs under xwayland for some reason) it's not present, audio runs normal on.

In 0.6.6 it's not present too.

https://github.com/labwc/labwc/assets/10681413/d7f0b372-4940-49a2-8b5b-441ca06a6ed8

**Comment by johanmalm** [comment] 2023-12-02 21:29
Any chance of testing with https://github.com/Nefsen402/sway/tree/scene-graph (i.e. `--branch=scene-graph`)

**Comment by Consolatis** [comment] 2023-12-03 01:29
> In falkon and chromium (which runs under xwayland for some reason) it's not present, audio runs normal on.

Hm.. That somewhat sounds like a presentation timer issue.
I don' think the new set_gamma handler has anything to do with this.

@stefonarch If you have the chance, could you retest via `MOZ_ENABLE_WAYLAND=0 firefox` (so running firefox via xwayland) ?

**Comment by stefonarch** [comment] 2023-12-03 07:38
> @stefonarch If you have the chance, could you retest via `MOZ_ENABLE_WAYLAND=0 firefox` (so running firefox via xwayland) ?

No issue if running in xwayland

>Any chance of testing with https://github.com/Nefsen402/sway/tree/scene-graph (i.e. --branch=scene-graph)

You mean compiling this branch and testing with sway? Probably I didn't get it right.

**Comment by johanmalm** [comment] 2023-12-03 07:54
> > Any chance of testing with https://github.com/Nefsen402/sway/tree/scene-graph (i.e. --branch=scene-graph)
> 
> You mean compiling this branch and testing with sway? Probably I didn't get it right.

Yes, because if we see the problem there, that points to a problem in `wlroots` rather than what we've done in `labwc`. Just helps to fault-find.

```
git clone --branch=scene-graph https://github.com/Nefsen402/labwc.git
cd sway
meson setup build
ninja -C build
./build/sway/sway
```

IIRC Super-d is linked to dmenu by default to launch an app

**Comment by stefonarch** [comment] 2023-12-04 17:47
Don't ask my why but this issue is gone here, updated both arch and labwc in the meantime.

**Comment by jp7677** [comment] 2023-12-04 17:49
I'm seeing the same or a very a similar issues also in other applications with `master` on https://github.com/labwc/labwc/commit/fcf21e1464e7dd9dc33a21c31a60d095b7f51b44 . I noticed this e.g. in tilix, clion or libre office writer. It looked liked the app wasn't responding anymore, but a mouse/stylus move over the window got the window updated again.

Sometime the "freeze" unfreezes itself. In `firefox`, extensively scrolling down or up by holding up/down arrow sometimes "stalled". Not sure though if this is the same issue.

**Comment by winteriscariot** [comment] 2023-12-05 20:25
So I think this issue is a broader firefox issue, not just video: at first, I thought it was just that, video in firefox, but even now, as I type this comment the output keeps freezing and waiting for mouse input: ie, i after a few seconds i stop seeing my words being typed until i jiggle the mouse again

this seems to be perhaps a firefox issue: running video in mpv doesn't have this same problem. i'm currently running firefox in Wayland native mode.

**Comment by johanmalm** [comment] 2023-12-08 22:13
@stefonarch @jp7677 @Flrian @heroin-moose 
Testing appreciated with the last couple of commits.

**Comment by stefonarch** [comment] 2023-12-09 07:47
I can't tell much probably as the issue had gone here after some day.

**Comment by jp7677** [comment] 2023-12-09 08:16
@johanmalm Thanks for looking into this. Yes, from a first glimpse, I cannot reproduce this issue anymore with any of the applications I had mentioned before. Cool!

PS: I got slightly confused at first because I have no hover effects anymore on SSD buttons (close, maximize etc) on https://github.com/labwc/labwc/commit/59dc4b702aab6d4b279ec87b2c0e016394be35ef, but I seem to remember someone mentioned this in a different issue.

**Comment by johanmalm** [comment] 2023-12-09 08:29
> @johanmalm Thanks for looking into this. Yes, from a first glimpse, I cannot reproduce this issue anymore with any of the applications I had mentioned before. Cool!

Great. Thanks for feedback.

Well I (unusually) had a sustained two hours in front of the computer yesterday and it happened twice to me... without the patches applied. I will run with it today, and close the issue if it doesn't happen again.

> PS: I got slightly confused at first because I have no hover effects anymore on SSD buttons (close, maximize etc) on [59dc4b7](https://github.com/labwc/labwc/commit/59dc4b702aab6d4b279ec87b2c0e016394be35ef), but I seem to remember someone mentioned this in a different issue.

Yes - apologies. I will sort out button-regressions before `0.7.0`. It was a tricky call. New contributor with a nice patch that I really wanted. I could spot the regressions, but the required refactoring was not trivial, so seemed easier/kinder/fairer to merge and then sort (yet to be done).

**Comment by jp7677** [comment] 2023-12-09 08:36
> Yes - apologies. I will sort out button-regressions before `0.7.0`. It was a tricky call. New contributor with a nice patch that I really wanted. I could spot the regressions, but the required refactoring was not trivial, so seemed easier/kinder/fairer to merge and then sort (yet to be done).

No worries, this is master after all. Thanks for all your work!

**Comment by johanmalm** [comment] 2023-12-09 20:04
No freezing today, so will close.

**Closed by johanmalm** 2023-12-09 20:04 UTC
Labels: bug, investigation required, regression
