### ISSUE TITLE
SIGPIPE when taking a screenshot in Overwatch 2.

### ISSUE THREAD

**Issue by FuzzyQuills** [labwc/labwc#890] opened 2023-04-23 14:19 UTC
Apparently happens in main.c at line 179, somewhere inside wlroots:
```
#0  __GI___libc_write (nbytes=2490422, buf=0x7fffb3cca030, fd=66) at ../sysdeps/unix/sysv/linux/write.c:26
#1  __GI___libc_write (fd=fd@entry=66, buf=0x7fffb3cca030, nbytes=nbytes@entry=2490422) at ../sysdeps/unix/sysv/linux/write.c:24
#2  0x00007ffff7f017f7 in write_selection_property_to_wl_client (fd=66, mask=<optimized out>, data=0x5555561bc670) at ../wlroots-0.16.2/xwayland/selection/incoming.c:111
#3  0x00007ffff7f7cae2 in wl_event_loop_dispatch (loop=0x5555555bdd00, timeout=timeout@entry=-1) at ../wayland-1.22.0/src/event-loop.c:1027
#4  0x00007ffff7f7d2d7 in wl_display_run (display=0x5555555bdc10) at ../wayland-1.22.0/src/wayland-server.c:1493
#5  0x0000555555568313 in main (argc=1, argv=0x7fffffffdf18) at ../src/main.c:179
```
Not sure if this is even a wlroots or a labwc bug; I only started getting this SIGPIPE crash a month ago. It's also embarassingly cost me a few competitive matches due to leaving early. (because labwc had terminated, taking everything with it)

Could it also be possible glibc broke something again?

To reproduce:
- Boot Overwatch 2 inside a labwc session.
- At login, in the menus, in match, practically anywhere else... press PrntScr to take a screenshot. Sometimes the first screenshot doesn't kill the compositor however, so just keep taking screenshots.
- Observe the session instantly quit after a few seconds.
- If GDB is open and attached to labwc, it reports a SIGPIPE.

**Comment by Consolatis** [comment] 2023-04-24 02:15
> press PrntScr to take a screenshot.

Are we talking about a built-in screenshot feature in Overwatch or about a labwc keybind?

**Comment by FuzzyQuills** [comment] 2023-04-24 02:41
> > press PrntScr to take a screenshot.
> 
> Are we talking about a built-in screenshot feature in Overwatch or about a labwc keybind?

This is an in-game keybind. (My actual screenshot bind is Super+PrntScr)

**Comment by Consolatis** [comment] 2023-04-24 03:30
Overwatch / Wine might be causing massive IO between xwayland and labwc/wlroots by some part of the implementation for the screenshot feature. I wonder if this could be the same underlying issue as these ones, e.g. we/wlroots or xwayland can't handle incoming data fast enough and thus something kills xwayland. And we still try to send data and then get a SIGPIPE.
- [Mapping a lot of windows at once using wl_shm gets Xwayland killed](https://gitlab.freedesktop.org/wayland/wayland/-/issues/237)
- [Blocked clients that received too many events get destroyed even though the Wayland connection is not broken](https://gitlab.freedesktop.org/wayland/wayland/-/issues/159)
- [Add connection buffer size control](https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/188)

A fix to prevent crashing labwc itself could be to something like this:
```diff
diff --git a/src/server.c b/src/server.c
index efc4e2f..a533838 100644
--- a/src/server.c
+++ b/src/server.c
@@ -226,6 +226,9 @@ server_init(struct server *server)
 		event_loop, SIGTERM, handle_sigterm, server->wl_display);
 	server->wl_event_loop = event_loop;
 
+	/* Don't let xwayland take us with it */
+	signal(SIGPIPE, SIG_IGN);
+
 	/*
 	 * The backend is a feature which abstracts the underlying input and
 	 * output hardware. The autocreate option will choose the most suitable
```

But it would still likely crash xwayland and thus all X11 applications.

**Comment by FuzzyQuills** [comment] 2023-04-24 03:44
Decided to test Sway and couldn't reproduce so this is potentially a labwc bug.

Is there a way to disable xwayland not starting until an X11 app is started? I have a feeling that might have something to do with it.

**Comment by Consolatis** [comment] 2023-04-24 04:12
sway ignores `SIGPIPE` (although it states the reason for that is its IPC system).
Does labwc still crash with the patch above?

> Is there a way to disable xwayland not starting until an X11 app is started? 

No, I don't think so. AFAIR we are unconditionally lazy-starting xwayland (and terminating it 10 seconds after the last client X11 disconnects). We could think about adding a config option to change that but before we are doing that I would prefer making sure that that is the actual reason for the `SIGPIPE` here and that there are no other potential fixes.

**Comment by FuzzyQuills** [comment] 2023-04-24 04:39
> sway ignores `SIGPIPE` (although it states the reason for that is its IPC system). Does labwc still crash with the patch above?
> 
> > Is there a way to disable xwayland not starting until an X11 app is started?
> 
> No, I don't think so. AFAIR we are unconditionally lazy-starting xwayland (and terminating it 10 seconds after the last client X11 disconnects). We could think about adding a config option to change that but before we are doing that I would prefer making sure that that is the actual reason for the `SIGPIPE` here and that there are no other potential fixes.

Soon as I get home, I'll test with the above patch. If you're correct and sway is indeed ignoring the SIGPIPE then it's also possible to fix screenshotting breaking it. (In Sway, Overwatch 2 kept running no matter how many times I fired the screenshot key)

**Comment by FuzzyQuills** [comment] 2023-04-24 08:33
I've just entered the patch myself on a local copy of master and can confirm ignoring SIGPIPE allows Overwatch 2 to continue running without crashing labwc. 

I'm now considering the possibility of adding a SIGPIPE handler that prints a warning as outright ignoring SIGPIPE might be a bad idea.

**Comment by Consolatis** [comment] 2023-04-24 11:48
Would you mind sharing that part of the log? I would be really interested to know who owns that fd and what the exact situation needs to be to end up with a `SIGPIPE`.

**Comment by FuzzyQuills** [comment] 2023-04-24 12:45
> Would you mind sharing that part of the log? I would be really interested to know who owns that fd and what the exact situation needs to be to end up with a `SIGPIPE`.

I've made my own branch again if you want to test that. (Called ow2-sigpipe-fix) in the meantime, soon as I'm done in Assetto Corsa, I'll get another log.

**Comment by FuzzyQuills** [comment] 2023-04-24 14:16
The relevant lines in the log are here: 
```
00:00:45.092 [DEBUG] [xwayland/selection/incoming.c:118] wrote 32768 (total 98304, remaining 1798198) of 1863734 bytes to fd 66
00:00:45.092 [DEBUG] [xwayland/selection/incoming.c:118] wrote 32768 (total 131072, remaining 1765430) of 1863734 bytes to fd 66
2023/04/24 23:57:56 Couldn't get input from stdin.
00:00:45.093 [ERROR] [xwayland/selection/incoming.c:113] write error to target fd 66: Broken pipe
```
32768 bytes looks like a rather huge amount, given I think the limit is 4096?
This is right after I press the screenshot key.

**Comment by Consolatis** [comment] 2023-04-24 14:38
Oh, I see. This is about the clipboard. Or to be precise the synchronization of the X11 clipboard and the wayland one. Overwatch likely just throws the screen content into the clipboard so its not doing something exotic at all.

Complete speculation at this point:
I assume the same issue can be triggered by copying something >= 2 MiB into the X11 clipboard (actual data, not just links to files). xwayland seems to then relay that clipboard content to wlroots and this part of the code has an issue somewhere in the chain. I will look into this later. This also explains why xwayland doesn't actually terminate, it seems completely unrelated to the wayland traffic itself. I wonder if wlroots should add the `SIGPIPE` handler (or ignore it) instead of hoping that compositors do it anyway.

**Comment by FuzzyQuills** [comment] 2023-04-24 14:43
> Oh, I see. This is about the clipboard. Or to be precise the synchronization of the X11 clipboard and the wayland one. Overwatch likely just throws the screen content into the clipboard so its not doing anything exotic at all.
> 
> Complete speculation at this point: I assume the same issue can be triggered by copying something >= 2 MiB into the X11 clipboard (actual data, not just links to files). xwayland seems to then relay that clipboard content to wlroots and this part of the code has an issue somewhere in the chain. I will look into it later. This also explains why xwayland doesn't actually terminate, it seems completely unrelated to the wayland traffic itself. I wonder if wlroots should add the `SIGPIPE` handler (or ignore it) instead of hoping that compositors do it anyway.

I wonder if this is why highlights have been empty video file containers for a while. Going to test something on X11 real quick.

**Comment by Consolatis** [comment] 2023-04-27 07:03
I tried to reproduce this with `xclip` and `wl-paste` but failed so far.

Do you use a wayland clipboard manager of some kind or some other application that automatically reads from the clipboard?

**Comment by FuzzyQuills** [comment] 2023-04-27 07:09
> I tried to reproduce this with `xclip` and `wl-paste` but failed so far.
> 
> Do you use a wayland clipboard manager of some kind or some other application that automatically reads from the clipboard?

Originally I didn't, but at some point I did add wl-paste to my autostart script. I think it was absent though at the time I made this issue.

**Comment by Consolatis** [comment] 2023-04-27 07:25
Got it to reproduce:
Open some x terminal applications (used xterm), required because wlroots prevents xclip from writing to the clipboard if no X11 application owns the focus.
In the x terminal emulator: `xclip -i < /some/file/with/some/mb`
On the wayland side: `wl-paste | head -c 1`.

So this this is about a wayland client requesting the clipboard set by an X11 application and prematurely closing its read fd.

**Comment by Consolatis** [comment] 2023-04-27 07:48
Added a missing `-p` to the reproducer above. Also figured out that gdb will cause a crash even if labwc is ignoring that signal, it can be worked around with `handle SIGPIPE nostop` in the gdb prompt before running labwc.

> And Overwatch 2, a fundamentally xwayland application, is triggering this. How strange.
> Is it doing this because the wl-paste command ultimately feeds the target application the data via the event queue?

Well, that is only part of the story, Overwatch seems to just set the clipboard which is totally fine.
The issue here is that some wayland application is starting to read the clipboard and then stop doing it before it was read completely. wlroots will keep relaying the remaining data to the wayland application but it closed its read end and that in turn causes the kernel to send a `SIGPIPE` to the process (e.g. labwc). As we are currently not ignoring that signal we will crash.

**Closed** 2023-04-27 17:21 UTC
Labels: bug, investigation required
