### ISSUE TITLE
Regression: Xwayland application not showing up on task switcher

### ISSUE THREAD

**Issue by BGazotti** [labwc/labwc#1341] opened 2023-12-19 03:08 UTC
Upgraded from 0.6.3 to 0.6.6 just now, and Wine on XWayland's window does not show up on the task switcher anymore; I can focus on it by clicking or using the taskbar (sfwbar). Additionally, it also now renders _under_ sfwbar while in full screen, essentially having the top cropped off. Does that warrant a separate issue?

labwc 0.6.6
wlroots 0.16.2
wayland 1.22.0

Thank you!

**Comment by Consolatis** [comment] 2023-12-19 03:36
> Wine on XWayland's window does not show up on the task switcher anymore;

Do you have a window rule with `skipWindowSwitcher` set by chance?
Otherwise wine windows \*should\* show up on the `A-Tab` dialog window switcher the same as all other X11 windows.

Or maybe the wine window somehow isn't focusable, e.g. our `view_wants_focus()` handler for xwayland doesn't like wine for some reason. CC @jlindgren90 

>  Additionally, it also now renders under sfwbar while in full screen, essentially having the top cropped off.

If sfwbar is configured to use anything other than the "overlay" layer the fullscreen window should indeed be on top of the panel. Does it work correctly with another fullscreen application (like some video / youtube in fullscreen)?

**Comment by BGazotti** [comment] 2023-12-19 03:43
> Do you have any window rule with `skipWindowSwitcher` set by chance?

I do not, just a rule for steam to have no window decorations. Worth noting is that ToggleAlwaysOnTop makes it render on top of all other windows but not sfwbar.

> Does it work correctly with another fullscreen application (like some video / youtube in fullscreen)?

Firefox in fullscreen works as expected and renders on top of the panel.  sfwbar is configured to use the "top" layer. Is that correct?

Also, just tested in 0.6.5, wine window displays in fullscreen AND shows up under alt+tab. There's some weirdness going on when trying to send it to another workspace, though - that causes sfwbar to vanish.

**Comment by jlindgren90** [comment] 2023-12-19 05:16
The window switcher issue would probably be solved by addressing #1139.

**Comment by Consolatis** [comment] 2023-12-19 06:30
Just saw that our focus detection logic for xwayland applications may also depend on the window decorations. I am not sure what `WM_CLASS` is used for your wine case but maybe it is matching your window rule; could you test if removing the window rule makes the application show up in `A-Tab`?

> Firefox in fullscreen works as expected and renders on top of the panel.

Hm.. so we somehow don't get the memo that the wine window is in fullscreen.

> sfwbar is configured to use the "top" layer. Is that correct?

Yes. Personally I prefer the "bottom" layer but "top" is fine as well.
In this specific case I assume setting it to the "bottom" layer will actually work around the issue and thus "fix" it for you.

**Comment by BGazotti** [comment] 2023-12-19 07:37
> could you test if removing the window rule makes the application show up in `A-Tab`

No luck, even without any window rules active. Config file for reference: [rc.xml](https://github.com/labwc/labwc/files/13712463/rc.txt)

Mind you, this does seem to be specific to wine and not an XWayland issue - launching kitty with the X11 backend makes it appear properly tagged as an xwayland application in Alt+Tab.

sfwbar workaround working, thank you!

**Comment by yuiiio** [comment] 2023-12-21 08:56
I can see same regression.
with wine(league of legends).
xprop
```
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		Initial state is Normal State.
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x2c, 0x0, 0x0, 0x0
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, WM_TAKE_FOCUS
```
and I try hack srv/view.c
```
--- a/src/view.c
+++ b/src/view.c
@@ -180,9 +180,10 @@ view_is_focusable_from(struct view *view, struct wlr_surface *prev)
 	 * guessing whether Globally Active views want focus, and will
 	 * probably be wrong some of the time.
 	 */
 	return (wants_focus == VIEW_WANTS_FOCUS_ALWAYS
 		|| (wants_focus == VIEW_WANTS_FOCUS_OFFER
-			&& prev && view_is_related(view, prev)));
+			&& prev && view_is_related(view, prev)) || (wants_focus == VIEW_WANTS_FOCUS_OFFER));
 }
```
this makes focusable league client window again.

**Comment by jp7677** [comment] 2023-12-21 09:45
The same issue can be observed using Jetbrains IDE's (CLion, Rider or IntelliJ), though only when their "New UI" is enabled. When the old UI is still enabled, the IDE's appear in the task switcher. 

Above hack does indeed makes those IDE's visible in the task switcher when the new UI  enabled.

**Comment by johanmalm** [comment] 2023-12-21 17:35
We're scheduled to release `0.7.0` tomorrow and feel that we're at a pretty stable point overall.

I think it's important to version-bump reasonably soon to get more people onto `wlroots 0.17` (which `0.7.0` builds against).
There are also quite a few PRs building up which we've purposefully delayed to observe a cool-down prior to release.

We take regressions seriously, but this one is tricky because getting focus-logic right with all of X11's idiosyncrasies is hard and it can at times feel like playing whack-a-mole. So, the risk with this one-liner change is that we cause a problem elsewhere.

Out of the options below, my preference is (1), but I welcome thoughts and feedback.

1. Release `0.7.0` tomorrow and fix this afterwards to give plenty of time for testing and stabilizing before the following release.
2. Patch with one-liner above and delay `0.7.0` by a week to gain confidence that it doesn't cause unwanted side-effects.

**Comment by jlindgren90** [comment] 2023-12-21 17:46
Going ahead with 0.7.0 is fine with me

**Comment by yuiiio** [comment] 2024-03-06 02:24
my issue seems fixes at https://github.com/labwc/labwc/pull/1533 thanks!

**Comment by Consolatis** [comment] 2024-03-06 03:17
Thanks for the confirmation.

I'll close this issue for now but feel free to comment if there are still X11 applications that should show up but do not.

**Closed by Consolatis** 2024-03-06 03:17 UTC
